// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignments.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO laptop_student_assignment (computer_id, student_id, class_id, academic_year)
VALUES ($1, $2, $3, $4)
RETURNING assignment_id, computer_id, student_id, class_id, academic_year
`

type CreateAssignmentParams struct {
	ComputerID   int64  `json:"computer_id"`
	StudentID    int64  `json:"student_id"`
	ClassID      int64  `json:"class_id"`
	AcademicYear string `json:"academic_year"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (LaptopStudentAssignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.ComputerID,
		arg.StudentID,
		arg.ClassID,
		arg.AcademicYear,
	)
	var i LaptopStudentAssignment
	err := row.Scan(
		&i.AssignmentID,
		&i.ComputerID,
		&i.StudentID,
		&i.ClassID,
		&i.AcademicYear,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM laptop_student_assignment WHERE assignment_id = $1
`

func (q *Queries) DeleteAssignment(ctx context.Context, assignmentID int64) error {
	_, err := q.db.Exec(ctx, deleteAssignment, assignmentID)
	return err
}

const getAssignment = `-- name: GetAssignment :one
SELECT assignment_id, computer_id, student_id, class_id, academic_year FROM laptop_student_assignment WHERE assignment_id = $1
`

func (q *Queries) GetAssignment(ctx context.Context, assignmentID int64) (LaptopStudentAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, assignmentID)
	var i LaptopStudentAssignment
	err := row.Scan(
		&i.AssignmentID,
		&i.ComputerID,
		&i.StudentID,
		&i.ClassID,
		&i.AcademicYear,
	)
	return i, err
}

const listAssignmentsByClass = `-- name: ListAssignmentsByClass :many
SELECT
    lsa.assignment_id, lsa.computer_id, lsa.student_id,
    lsa.class_id, lsa.academic_year,
    s.full_name AS student_name
FROM laptop_student_assignment lsa
JOIN student s ON s.student_id = lsa.student_id
WHERE lsa.class_id = $1
ORDER BY lsa.academic_year DESC, s.full_name
`

type ListAssignmentsByClassRow struct {
	AssignmentID int64  `json:"assignment_id"`
	ComputerID   int64  `json:"computer_id"`
	StudentID    int64  `json:"student_id"`
	ClassID      int64  `json:"class_id"`
	AcademicYear string `json:"academic_year"`
	StudentName  string `json:"student_name"`
}

func (q *Queries) ListAssignmentsByClass(ctx context.Context, classID int64) ([]ListAssignmentsByClassRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentsByClassRow
	for rows.Next() {
		var i ListAssignmentsByClassRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.ComputerID,
			&i.StudentID,
			&i.ClassID,
			&i.AcademicYear,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsByLaptop = `-- name: ListAssignmentsByLaptop :many
SELECT
    lsa.assignment_id, lsa.computer_id, lsa.student_id,
    lsa.class_id, lsa.academic_year,
    s.full_name AS student_name,
    sc.course, sc.class_label, sc.shift, sc.cycle_id
FROM laptop_student_assignment lsa
JOIN student s   ON s.student_id     = lsa.student_id
JOIN school_class sc ON sc.class_id  = lsa.class_id
WHERE lsa.computer_id = $1
ORDER BY lsa.academic_year DESC, sc.shift
`

type ListAssignmentsByLaptopRow struct {
	AssignmentID int64     `json:"assignment_id"`
	ComputerID   int64     `json:"computer_id"`
	StudentID    int64     `json:"student_id"`
	ClassID      int64     `json:"class_id"`
	AcademicYear string    `json:"academic_year"`
	StudentName  string    `json:"student_name"`
	Course       int16     `json:"course"`
	ClassLabel   string    `json:"class_label"`
	Shift        ShiftEnum `json:"shift"`
	CycleID      int64     `json:"cycle_id"`
}

func (q *Queries) ListAssignmentsByLaptop(ctx context.Context, computerID int64) ([]ListAssignmentsByLaptopRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByLaptop, computerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentsByLaptopRow
	for rows.Next() {
		var i ListAssignmentsByLaptopRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.ComputerID,
			&i.StudentID,
			&i.ClassID,
			&i.AcademicYear,
			&i.StudentName,
			&i.Course,
			&i.ClassLabel,
			&i.Shift,
			&i.CycleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE laptop_student_assignment
SET
    student_id    = COALESCE($1,    student_id),
    class_id      = COALESCE($2,      class_id),
    academic_year = COALESCE($3, academic_year)
WHERE assignment_id = $4
RETURNING assignment_id, computer_id, student_id, class_id, academic_year
`

type UpdateAssignmentParams struct {
	StudentID    pgtype.Int8 `json:"student_id"`
	ClassID      pgtype.Int8 `json:"class_id"`
	AcademicYear pgtype.Text `json:"academic_year"`
	AssignmentID int64       `json:"assignment_id"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (LaptopStudentAssignment, error) {
	row := q.db.QueryRow(ctx, updateAssignment,
		arg.StudentID,
		arg.ClassID,
		arg.AcademicYear,
		arg.AssignmentID,
	)
	var i LaptopStudentAssignment
	err := row.Scan(
		&i.AssignmentID,
		&i.ComputerID,
		&i.StudentID,
		&i.ClassID,
		&i.AcademicYear,
	)
	return i, err
}
