// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbsqlc

import (
	"context"
)

const getAuditLog = `-- name: GetAuditLog :many
SELECT audit_id, table_name, record_id, event_type, old_values, new_values, changed_by_app_user_id, changed_by_username, changed_at
FROM audit_log
WHERE table_name = $1 AND record_id = $2
ORDER BY changed_at DESC
`

type GetAuditLogParams struct {
	TableName string `json:"table_name"`
	RecordID  int64  `json:"record_id"`
}

func (q *Queries) GetAuditLog(ctx context.Context, arg GetAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLog, arg.TableName, arg.RecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.AuditID,
			&i.TableName,
			&i.RecordID,
			&i.EventType,
			&i.OldValues,
			&i.NewValues,
			&i.ChangedByAppUserID,
			&i.ChangedByUsername,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (
    table_name, record_id, event_type,
    old_values, new_values,
    changed_by_app_user_id, changed_by_username
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
`

type InsertAuditLogParams struct {
	TableName          string         `json:"table_name"`
	RecordID           int64          `json:"record_id"`
	EventType          AuditEventEnum `json:"event_type"`
	OldValues          []byte         `json:"old_values"`
	NewValues          []byte         `json:"new_values"`
	ChangedByAppUserID int64          `json:"changed_by_app_user_id"`
	ChangedByUsername  string         `json:"changed_by_username"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.TableName,
		arg.RecordID,
		arg.EventType,
		arg.OldValues,
		arg.NewValues,
		arg.ChangedByAppUserID,
		arg.ChangedByUsername,
	)
	return err
}
