// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbsqlc

import (
	"context"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT app_user_id, username, password_hash, role_id
FROM app_user
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i AppUser
	err := row.Scan(
		&i.AppUserID,
		&i.Username,
		&i.PasswordHash,
		&i.RoleID,
	)
	return i, err
}
