// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brands.sql

package dbsqlc

import (
	"context"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO brand (name) VALUES ($1) RETURNING brand_id, name
`

func (q *Queries) CreateBrand(ctx context.Context, name string) (Brand, error) {
	row := q.db.QueryRow(ctx, createBrand, name)
	var i Brand
	err := row.Scan(&i.BrandID, &i.Name)
	return i, err
}

const deleteBrand = `-- name: DeleteBrand :exec
DELETE FROM brand WHERE brand_id = $1
`

func (q *Queries) DeleteBrand(ctx context.Context, brandID int64) error {
	_, err := q.db.Exec(ctx, deleteBrand, brandID)
	return err
}

const getBrand = `-- name: GetBrand :one
SELECT brand_id, name FROM brand WHERE brand_id = $1
`

func (q *Queries) GetBrand(ctx context.Context, brandID int64) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrand, brandID)
	var i Brand
	err := row.Scan(&i.BrandID, &i.Name)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT brand_id, name FROM brand ORDER BY name
`

func (q *Queries) ListBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(&i.BrandID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE brand SET name = $2 WHERE brand_id = $1 RETURNING brand_id, name
`

type UpdateBrandParams struct {
	BrandID int64  `json:"brand_id"`
	Name    string `json:"name"`
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, updateBrand, arg.BrandID, arg.Name)
	var i Brand
	err := row.Scan(&i.BrandID, &i.Name)
	return i, err
}
