// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: centers.sql

package dbsqlc

import (
	"context"
)

const createCenter = `-- name: CreateCenter :one
INSERT INTO center (name)
VALUES ($1)
RETURNING center_id, name
`

func (q *Queries) CreateCenter(ctx context.Context, name string) (Center, error) {
	row := q.db.QueryRow(ctx, createCenter, name)
	var i Center
	err := row.Scan(&i.CenterID, &i.Name)
	return i, err
}

const deleteCenter = `-- name: DeleteCenter :exec
DELETE FROM center
WHERE center_id = $1
`

func (q *Queries) DeleteCenter(ctx context.Context, centerID int64) error {
	_, err := q.db.Exec(ctx, deleteCenter, centerID)
	return err
}

const listCenters = `-- name: ListCenters :many
SELECT center_id, name
FROM center
ORDER BY center_id
`

func (q *Queries) ListCenters(ctx context.Context) ([]Center, error) {
	rows, err := q.db.Query(ctx, listCenters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Center
	for rows.Next() {
		var i Center
		if err := rows.Scan(&i.CenterID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCenter = `-- name: UpdateCenter :one
UPDATE center
SET name = $1
WHERE center_id = $2
RETURNING center_id, name
`

type UpdateCenterParams struct {
	Name     string `json:"name"`
	CenterID int64  `json:"center_id"`
}

func (q *Queries) UpdateCenter(ctx context.Context, arg UpdateCenterParams) (Center, error) {
	row := q.db.QueryRow(ctx, updateCenter, arg.Name, arg.CenterID)
	var i Center
	err := row.Scan(&i.CenterID, &i.Name)
	return i, err
}
