// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: computers.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComputer = `-- name: CreateComputer :one
INSERT INTO computer (hostname, room_id, observations, created_by_app_user_id)
VALUES ($1, $2, $3, $4)
RETURNING computer_id, hostname, room_id, observations, created_by_app_user_id, created_at, updated_at
`

type CreateComputerParams struct {
	Hostname           string      `json:"hostname"`
	RoomID             pgtype.Int8 `json:"room_id"`
	Observations       pgtype.Text `json:"observations"`
	CreatedByAppUserID int64       `json:"created_by_app_user_id"`
}

func (q *Queries) CreateComputer(ctx context.Context, arg CreateComputerParams) (Computer, error) {
	row := q.db.QueryRow(ctx, createComputer,
		arg.Hostname,
		arg.RoomID,
		arg.Observations,
		arg.CreatedByAppUserID,
	)
	var i Computer
	err := row.Scan(
		&i.ComputerID,
		&i.Hostname,
		&i.RoomID,
		&i.Observations,
		&i.CreatedByAppUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComputer = `-- name: DeleteComputer :exec
DELETE FROM computer WHERE computer_id = $1
`

func (q *Queries) DeleteComputer(ctx context.Context, computerID int64) error {
	_, err := q.db.Exec(ctx, deleteComputer, computerID)
	return err
}

const getComputerBase = `-- name: GetComputerBase :one
SELECT computer_id, hostname, room_id, observations, created_by_app_user_id, created_at, updated_at FROM computer WHERE computer_id = $1
`

func (q *Queries) GetComputerBase(ctx context.Context, computerID int64) (Computer, error) {
	row := q.db.QueryRow(ctx, getComputerBase, computerID)
	var i Computer
	err := row.Scan(
		&i.ComputerID,
		&i.Hostname,
		&i.RoomID,
		&i.Observations,
		&i.CreatedByAppUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComputers = `-- name: ListComputers :many
SELECT
    c.computer_id, c.hostname, c.room_id, c.observations, c.created_by_app_user_id, c.created_at, c.updated_at,
    CASE WHEN d.computer_id IS NOT NULL THEN 'desktop' ELSE 'laptop' END AS computer_type
FROM computer c
LEFT JOIN desktop d ON d.computer_id = c.computer_id
ORDER BY c.computer_id
`

type ListComputersRow struct {
	ComputerID         int64              `json:"computer_id"`
	Hostname           string             `json:"hostname"`
	RoomID             pgtype.Int8        `json:"room_id"`
	Observations       pgtype.Text        `json:"observations"`
	CreatedByAppUserID int64              `json:"created_by_app_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ComputerType       string             `json:"computer_type"`
}

// Returns all computers with computer_type derived from which subtable has a row.
func (q *Queries) ListComputers(ctx context.Context) ([]ListComputersRow, error) {
	rows, err := q.db.Query(ctx, listComputers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComputersRow
	for rows.Next() {
		var i ListComputersRow
		if err := rows.Scan(
			&i.ComputerID,
			&i.Hostname,
			&i.RoomID,
			&i.Observations,
			&i.CreatedByAppUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ComputerType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComputerBase = `-- name: UpdateComputerBase :one
UPDATE computer
SET
    hostname     = COALESCE($1,     hostname),
    room_id      = COALESCE($2,      room_id),
    observations = COALESCE($3,  observations),
    updated_at   = now()
WHERE computer_id = $4
RETURNING computer_id, hostname, room_id, observations, created_by_app_user_id, created_at, updated_at
`

type UpdateComputerBaseParams struct {
	Hostname     pgtype.Text `json:"hostname"`
	RoomID       pgtype.Int8 `json:"room_id"`
	Observations pgtype.Text `json:"observations"`
	ComputerID   int64       `json:"computer_id"`
}

func (q *Queries) UpdateComputerBase(ctx context.Context, arg UpdateComputerBaseParams) (Computer, error) {
	row := q.db.QueryRow(ctx, updateComputerBase,
		arg.Hostname,
		arg.RoomID,
		arg.Observations,
		arg.ComputerID,
	)
	var i Computer
	err := row.Scan(
		&i.ComputerID,
		&i.Hostname,
		&i.RoomID,
		&i.Observations,
		&i.CreatedByAppUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
