// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cpus.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCPU = `-- name: CreateCPU :one
INSERT INTO cpu (model_name, benchmark_score)
VALUES ($1, $2)
RETURNING cpu_id, model_name, benchmark_score
`

type CreateCPUParams struct {
	ModelName      string      `json:"model_name"`
	BenchmarkScore pgtype.Int4 `json:"benchmark_score"`
}

func (q *Queries) CreateCPU(ctx context.Context, arg CreateCPUParams) (Cpu, error) {
	row := q.db.QueryRow(ctx, createCPU, arg.ModelName, arg.BenchmarkScore)
	var i Cpu
	err := row.Scan(&i.CpuID, &i.ModelName, &i.BenchmarkScore)
	return i, err
}

const deleteCPU = `-- name: DeleteCPU :exec
DELETE FROM cpu
WHERE cpu_id = $1
`

func (q *Queries) DeleteCPU(ctx context.Context, cpuID int64) error {
	_, err := q.db.Exec(ctx, deleteCPU, cpuID)
	return err
}

const listCPUs = `-- name: ListCPUs :many
SELECT cpu_id, model_name, benchmark_score
FROM cpu
ORDER BY cpu_id
`

func (q *Queries) ListCPUs(ctx context.Context) ([]Cpu, error) {
	rows, err := q.db.Query(ctx, listCPUs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cpu
	for rows.Next() {
		var i Cpu
		if err := rows.Scan(&i.CpuID, &i.ModelName, &i.BenchmarkScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCPU = `-- name: UpdateCPU :one
UPDATE cpu
SET
    model_name      = COALESCE($1,      model_name),
    benchmark_score = COALESCE($2, benchmark_score)
WHERE cpu_id = $3
RETURNING cpu_id, model_name, benchmark_score
`

type UpdateCPUParams struct {
	ModelName      pgtype.Text `json:"model_name"`
	BenchmarkScore pgtype.Int4 `json:"benchmark_score"`
	CpuID          int64       `json:"cpu_id"`
}

func (q *Queries) UpdateCPU(ctx context.Context, arg UpdateCPUParams) (Cpu, error) {
	row := q.db.QueryRow(ctx, updateCPU, arg.ModelName, arg.BenchmarkScore, arg.CpuID)
	var i Cpu
	err := row.Scan(&i.CpuID, &i.ModelName, &i.BenchmarkScore)
	return i, err
}
