// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cycles.sql

package dbsqlc

import (
	"context"
)

const createCycle = `-- name: CreateCycle :one
INSERT INTO cycle (name) VALUES ($1) RETURNING cycle_id, name
`

func (q *Queries) CreateCycle(ctx context.Context, name string) (Cycle, error) {
	row := q.db.QueryRow(ctx, createCycle, name)
	var i Cycle
	err := row.Scan(&i.CycleID, &i.Name)
	return i, err
}

const deleteCycle = `-- name: DeleteCycle :exec
DELETE FROM cycle WHERE cycle_id = $1
`

func (q *Queries) DeleteCycle(ctx context.Context, cycleID int64) error {
	_, err := q.db.Exec(ctx, deleteCycle, cycleID)
	return err
}

const listCycles = `-- name: ListCycles :many
SELECT cycle_id, name FROM cycle ORDER BY name
`

func (q *Queries) ListCycles(ctx context.Context) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, listCycles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cycle
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(&i.CycleID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCycle = `-- name: UpdateCycle :one
UPDATE cycle SET name = $2 WHERE cycle_id = $1 RETURNING cycle_id, name
`

type UpdateCycleParams struct {
	CycleID int64  `json:"cycle_id"`
	Name    string `json:"name"`
}

func (q *Queries) UpdateCycle(ctx context.Context, arg UpdateCycleParams) (Cycle, error) {
	row := q.db.QueryRow(ctx, updateCycle, arg.CycleID, arg.Name)
	var i Cycle
	err := row.Scan(&i.CycleID, &i.Name)
	return i, err
}
