// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: desktop_models.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDesktopModel = `-- name: CreateDesktopModel :one
INSERT INTO desktop_model (
    brand_id, model_name, cpu_id,
    base_ram_gb, base_ram_type,
    base_storage_gb, base_storage_type, base_os_id
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8
) RETURNING desktop_model_id, brand_id, model_name, cpu_id, base_ram_gb, base_ram_type, base_storage_gb, base_storage_type, base_os_id
`

type CreateDesktopModelParams struct {
	BrandID         int64           `json:"brand_id"`
	ModelName       string          `json:"model_name"`
	CpuID           pgtype.Int8     `json:"cpu_id"`
	BaseRamGb       int32           `json:"base_ram_gb"`
	BaseRamType     RamTypeEnum     `json:"base_ram_type"`
	BaseStorageGb   int32           `json:"base_storage_gb"`
	BaseStorageType StorageTypeEnum `json:"base_storage_type"`
	BaseOsID        pgtype.Int8     `json:"base_os_id"`
}

func (q *Queries) CreateDesktopModel(ctx context.Context, arg CreateDesktopModelParams) (DesktopModel, error) {
	row := q.db.QueryRow(ctx, createDesktopModel,
		arg.BrandID,
		arg.ModelName,
		arg.CpuID,
		arg.BaseRamGb,
		arg.BaseRamType,
		arg.BaseStorageGb,
		arg.BaseStorageType,
		arg.BaseOsID,
	)
	var i DesktopModel
	err := row.Scan(
		&i.DesktopModelID,
		&i.BrandID,
		&i.ModelName,
		&i.CpuID,
		&i.BaseRamGb,
		&i.BaseRamType,
		&i.BaseStorageGb,
		&i.BaseStorageType,
		&i.BaseOsID,
	)
	return i, err
}

const deleteDesktopModel = `-- name: DeleteDesktopModel :exec
DELETE FROM desktop_model WHERE desktop_model_id = $1
`

func (q *Queries) DeleteDesktopModel(ctx context.Context, desktopModelID int64) error {
	_, err := q.db.Exec(ctx, deleteDesktopModel, desktopModelID)
	return err
}

const getDesktopModel = `-- name: GetDesktopModel :one
SELECT dm.desktop_model_id, dm.brand_id, dm.model_name, dm.cpu_id, dm.base_ram_gb, dm.base_ram_type, dm.base_storage_gb, dm.base_storage_type, dm.base_os_id, b.name AS brand_name
FROM desktop_model dm
JOIN brand b ON b.brand_id = dm.brand_id
WHERE dm.desktop_model_id = $1
`

type GetDesktopModelRow struct {
	DesktopModelID  int64           `json:"desktop_model_id"`
	BrandID         int64           `json:"brand_id"`
	ModelName       string          `json:"model_name"`
	CpuID           pgtype.Int8     `json:"cpu_id"`
	BaseRamGb       int32           `json:"base_ram_gb"`
	BaseRamType     RamTypeEnum     `json:"base_ram_type"`
	BaseStorageGb   int32           `json:"base_storage_gb"`
	BaseStorageType StorageTypeEnum `json:"base_storage_type"`
	BaseOsID        pgtype.Int8     `json:"base_os_id"`
	BrandName       string          `json:"brand_name"`
}

func (q *Queries) GetDesktopModel(ctx context.Context, desktopModelID int64) (GetDesktopModelRow, error) {
	row := q.db.QueryRow(ctx, getDesktopModel, desktopModelID)
	var i GetDesktopModelRow
	err := row.Scan(
		&i.DesktopModelID,
		&i.BrandID,
		&i.ModelName,
		&i.CpuID,
		&i.BaseRamGb,
		&i.BaseRamType,
		&i.BaseStorageGb,
		&i.BaseStorageType,
		&i.BaseOsID,
		&i.BrandName,
	)
	return i, err
}

const listDesktopModels = `-- name: ListDesktopModels :many
SELECT dm.desktop_model_id, dm.brand_id, dm.model_name, dm.cpu_id, dm.base_ram_gb, dm.base_ram_type, dm.base_storage_gb, dm.base_storage_type, dm.base_os_id, b.name AS brand_name
FROM desktop_model dm
JOIN brand b ON b.brand_id = dm.brand_id
ORDER BY b.name, dm.model_name
`

type ListDesktopModelsRow struct {
	DesktopModelID  int64           `json:"desktop_model_id"`
	BrandID         int64           `json:"brand_id"`
	ModelName       string          `json:"model_name"`
	CpuID           pgtype.Int8     `json:"cpu_id"`
	BaseRamGb       int32           `json:"base_ram_gb"`
	BaseRamType     RamTypeEnum     `json:"base_ram_type"`
	BaseStorageGb   int32           `json:"base_storage_gb"`
	BaseStorageType StorageTypeEnum `json:"base_storage_type"`
	BaseOsID        pgtype.Int8     `json:"base_os_id"`
	BrandName       string          `json:"brand_name"`
}

func (q *Queries) ListDesktopModels(ctx context.Context) ([]ListDesktopModelsRow, error) {
	rows, err := q.db.Query(ctx, listDesktopModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDesktopModelsRow
	for rows.Next() {
		var i ListDesktopModelsRow
		if err := rows.Scan(
			&i.DesktopModelID,
			&i.BrandID,
			&i.ModelName,
			&i.CpuID,
			&i.BaseRamGb,
			&i.BaseRamType,
			&i.BaseStorageGb,
			&i.BaseStorageType,
			&i.BaseOsID,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDesktopModel = `-- name: UpdateDesktopModel :one
UPDATE desktop_model
SET
    brand_id          = COALESCE($1,          brand_id),
    model_name        = COALESCE($2,        model_name),
    cpu_id            = COALESCE($3,            cpu_id),
    base_ram_gb       = COALESCE($4,       base_ram_gb),
    base_ram_type     = COALESCE($5,     base_ram_type),
    base_storage_gb   = COALESCE($6,   base_storage_gb),
    base_storage_type = COALESCE($7, base_storage_type),
    base_os_id        = COALESCE($8,        base_os_id)
WHERE desktop_model_id = $9
RETURNING desktop_model_id, brand_id, model_name, cpu_id, base_ram_gb, base_ram_type, base_storage_gb, base_storage_type, base_os_id
`

type UpdateDesktopModelParams struct {
	BrandID         pgtype.Int8         `json:"brand_id"`
	ModelName       pgtype.Text         `json:"model_name"`
	CpuID           pgtype.Int8         `json:"cpu_id"`
	BaseRamGb       pgtype.Int4         `json:"base_ram_gb"`
	BaseRamType     NullRamTypeEnum     `json:"base_ram_type"`
	BaseStorageGb   pgtype.Int4         `json:"base_storage_gb"`
	BaseStorageType NullStorageTypeEnum `json:"base_storage_type"`
	BaseOsID        pgtype.Int8         `json:"base_os_id"`
	DesktopModelID  int64               `json:"desktop_model_id"`
}

func (q *Queries) UpdateDesktopModel(ctx context.Context, arg UpdateDesktopModelParams) (DesktopModel, error) {
	row := q.db.QueryRow(ctx, updateDesktopModel,
		arg.BrandID,
		arg.ModelName,
		arg.CpuID,
		arg.BaseRamGb,
		arg.BaseRamType,
		arg.BaseStorageGb,
		arg.BaseStorageType,
		arg.BaseOsID,
		arg.DesktopModelID,
	)
	var i DesktopModel
	err := row.Scan(
		&i.DesktopModelID,
		&i.BrandID,
		&i.ModelName,
		&i.CpuID,
		&i.BaseRamGb,
		&i.BaseRamType,
		&i.BaseStorageGb,
		&i.BaseStorageType,
		&i.BaseOsID,
	)
	return i, err
}
