// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: desktops.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDesktop = `-- name: CreateDesktop :one
INSERT INTO desktop (
    computer_id, desktop_model_id, cpu_id,
    ram_gb, ram_type, storage_gb, storage_type,
    os_id, equipment_user_id, has_wifi_card, mac_address
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10, $11
) RETURNING computer_id, desktop_model_id, cpu_id, ram_gb, ram_type, storage_gb, storage_type, os_id, equipment_user_id, has_wifi_card, mac_address
`

type CreateDesktopParams struct {
	ComputerID      int64               `json:"computer_id"`
	DesktopModelID  pgtype.Int8         `json:"desktop_model_id"`
	CpuID           pgtype.Int8         `json:"cpu_id"`
	RamGb           pgtype.Int4         `json:"ram_gb"`
	RamType         NullRamTypeEnum     `json:"ram_type"`
	StorageGb       pgtype.Int4         `json:"storage_gb"`
	StorageType     NullStorageTypeEnum `json:"storage_type"`
	OsID            pgtype.Int8         `json:"os_id"`
	EquipmentUserID pgtype.Int8         `json:"equipment_user_id"`
	HasWifiCard     bool                `json:"has_wifi_card"`
	MacAddress      pgtype.Text         `json:"mac_address"`
}

func (q *Queries) CreateDesktop(ctx context.Context, arg CreateDesktopParams) (Desktop, error) {
	row := q.db.QueryRow(ctx, createDesktop,
		arg.ComputerID,
		arg.DesktopModelID,
		arg.CpuID,
		arg.RamGb,
		arg.RamType,
		arg.StorageGb,
		arg.StorageType,
		arg.OsID,
		arg.EquipmentUserID,
		arg.HasWifiCard,
		arg.MacAddress,
	)
	var i Desktop
	err := row.Scan(
		&i.ComputerID,
		&i.DesktopModelID,
		&i.CpuID,
		&i.RamGb,
		&i.RamType,
		&i.StorageGb,
		&i.StorageType,
		&i.OsID,
		&i.EquipmentUserID,
		&i.HasWifiCard,
		&i.MacAddress,
	)
	return i, err
}

const getDesktop = `-- name: GetDesktop :one
SELECT
    c.computer_id, c.hostname, c.room_id, c.observations,
    c.created_by_app_user_id, c.created_at, c.updated_at,
    d.desktop_model_id,
    COALESCE(d.cpu_id,       CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.cpu_id       END) AS cpu_id,
    COALESCE(d.ram_gb,       CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.base_ram_gb       END) AS ram_gb,
    COALESCE(d.ram_type,     CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.base_ram_type     END) AS ram_type,
    COALESCE(d.storage_gb,   CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.base_storage_gb   END) AS storage_gb,
    COALESCE(d.storage_type, CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.base_storage_type END) AS storage_type,
    COALESCE(d.os_id,        CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.base_os_id        END) AS os_id,
    d.equipment_user_id, d.has_wifi_card, d.mac_address
FROM computer c
INNER JOIN desktop d ON d.computer_id = c.computer_id
LEFT JOIN desktop_model dm ON dm.desktop_model_id = d.desktop_model_id
WHERE c.computer_id = $1
`

type GetDesktopRow struct {
	ComputerID         int64               `json:"computer_id"`
	Hostname           string              `json:"hostname"`
	RoomID             pgtype.Int8         `json:"room_id"`
	Observations       pgtype.Text         `json:"observations"`
	CreatedByAppUserID int64               `json:"created_by_app_user_id"`
	CreatedAt          pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `json:"updated_at"`
	DesktopModelID     pgtype.Int8         `json:"desktop_model_id"`
	CpuID              pgtype.Int8         `json:"cpu_id"`
	RamGb              pgtype.Int4         `json:"ram_gb"`
	RamType            NullRamTypeEnum     `json:"ram_type"`
	StorageGb          pgtype.Int4         `json:"storage_gb"`
	StorageType        NullStorageTypeEnum `json:"storage_type"`
	OsID               pgtype.Int8         `json:"os_id"`
	EquipmentUserID    pgtype.Int8         `json:"equipment_user_id"`
	HasWifiCard        bool                `json:"has_wifi_card"`
	MacAddress         pgtype.Text         `json:"mac_address"`
}

func (q *Queries) GetDesktop(ctx context.Context, computerID int64) (GetDesktopRow, error) {
	row := q.db.QueryRow(ctx, getDesktop, computerID)
	var i GetDesktopRow
	err := row.Scan(
		&i.ComputerID,
		&i.Hostname,
		&i.RoomID,
		&i.Observations,
		&i.CreatedByAppUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DesktopModelID,
		&i.CpuID,
		&i.RamGb,
		&i.RamType,
		&i.StorageGb,
		&i.StorageType,
		&i.OsID,
		&i.EquipmentUserID,
		&i.HasWifiCard,
		&i.MacAddress,
	)
	return i, err
}

const listDesktops = `-- name: ListDesktops :many
SELECT
    c.computer_id, c.hostname, c.room_id, c.observations,
    c.created_by_app_user_id, c.created_at, c.updated_at,
    d.desktop_model_id,
    COALESCE(d.cpu_id,       CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.cpu_id       END) AS cpu_id,
    COALESCE(d.ram_gb,       CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.base_ram_gb       END) AS ram_gb,
    COALESCE(d.ram_type,     CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.base_ram_type     END) AS ram_type,
    COALESCE(d.storage_gb,   CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.base_storage_gb   END) AS storage_gb,
    COALESCE(d.storage_type, CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.base_storage_type END) AS storage_type,
    COALESCE(d.os_id,        CASE WHEN dm.desktop_model_id IS NOT NULL THEN dm.base_os_id        END) AS os_id,
    d.equipment_user_id, d.has_wifi_card, d.mac_address
FROM computer c
INNER JOIN desktop d ON d.computer_id = c.computer_id
LEFT JOIN desktop_model dm ON dm.desktop_model_id = d.desktop_model_id
ORDER BY c.computer_id
`

type ListDesktopsRow struct {
	ComputerID         int64               `json:"computer_id"`
	Hostname           string              `json:"hostname"`
	RoomID             pgtype.Int8         `json:"room_id"`
	Observations       pgtype.Text         `json:"observations"`
	CreatedByAppUserID int64               `json:"created_by_app_user_id"`
	CreatedAt          pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `json:"updated_at"`
	DesktopModelID     pgtype.Int8         `json:"desktop_model_id"`
	CpuID              pgtype.Int8         `json:"cpu_id"`
	RamGb              pgtype.Int4         `json:"ram_gb"`
	RamType            NullRamTypeEnum     `json:"ram_type"`
	StorageGb          pgtype.Int4         `json:"storage_gb"`
	StorageType        NullStorageTypeEnum `json:"storage_type"`
	OsID               pgtype.Int8         `json:"os_id"`
	EquipmentUserID    pgtype.Int8         `json:"equipment_user_id"`
	HasWifiCard        bool                `json:"has_wifi_card"`
	MacAddress         pgtype.Text         `json:"mac_address"`
}

func (q *Queries) ListDesktops(ctx context.Context) ([]ListDesktopsRow, error) {
	rows, err := q.db.Query(ctx, listDesktops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDesktopsRow
	for rows.Next() {
		var i ListDesktopsRow
		if err := rows.Scan(
			&i.ComputerID,
			&i.Hostname,
			&i.RoomID,
			&i.Observations,
			&i.CreatedByAppUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DesktopModelID,
			&i.CpuID,
			&i.RamGb,
			&i.RamType,
			&i.StorageGb,
			&i.StorageType,
			&i.OsID,
			&i.EquipmentUserID,
			&i.HasWifiCard,
			&i.MacAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDesktop = `-- name: UpdateDesktop :one
UPDATE desktop
SET
    desktop_model_id  = COALESCE($1,  desktop_model_id),
    cpu_id            = COALESCE($2,            cpu_id),
    ram_gb            = COALESCE($3,            ram_gb),
    ram_type          = COALESCE($4,          ram_type),
    storage_gb        = COALESCE($5,        storage_gb),
    storage_type      = COALESCE($6,      storage_type),
    os_id             = COALESCE($7,             os_id),
    equipment_user_id = COALESCE($8, equipment_user_id),
    has_wifi_card     = COALESCE($9,     has_wifi_card),
    mac_address       = COALESCE($10,       mac_address)
WHERE computer_id = $11
RETURNING computer_id, desktop_model_id, cpu_id, ram_gb, ram_type, storage_gb, storage_type, os_id, equipment_user_id, has_wifi_card, mac_address
`

type UpdateDesktopParams struct {
	DesktopModelID  pgtype.Int8         `json:"desktop_model_id"`
	CpuID           pgtype.Int8         `json:"cpu_id"`
	RamGb           pgtype.Int4         `json:"ram_gb"`
	RamType         NullRamTypeEnum     `json:"ram_type"`
	StorageGb       pgtype.Int4         `json:"storage_gb"`
	StorageType     NullStorageTypeEnum `json:"storage_type"`
	OsID            pgtype.Int8         `json:"os_id"`
	EquipmentUserID pgtype.Int8         `json:"equipment_user_id"`
	HasWifiCard     pgtype.Bool         `json:"has_wifi_card"`
	MacAddress      pgtype.Text         `json:"mac_address"`
	ComputerID      int64               `json:"computer_id"`
}

func (q *Queries) UpdateDesktop(ctx context.Context, arg UpdateDesktopParams) (Desktop, error) {
	row := q.db.QueryRow(ctx, updateDesktop,
		arg.DesktopModelID,
		arg.CpuID,
		arg.RamGb,
		arg.RamType,
		arg.StorageGb,
		arg.StorageType,
		arg.OsID,
		arg.EquipmentUserID,
		arg.HasWifiCard,
		arg.MacAddress,
		arg.ComputerID,
	)
	var i Desktop
	err := row.Scan(
		&i.ComputerID,
		&i.DesktopModelID,
		&i.CpuID,
		&i.RamGb,
		&i.RamType,
		&i.StorageGb,
		&i.StorageType,
		&i.OsID,
		&i.EquipmentUserID,
		&i.HasWifiCard,
		&i.MacAddress,
	)
	return i, err
}
