// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipment_users.sql

package dbsqlc

import (
	"context"
)

const createEquipmentUser = `-- name: CreateEquipmentUser :one
INSERT INTO equipment_user (name)
VALUES ($1)
RETURNING equipment_user_id, name
`

func (q *Queries) CreateEquipmentUser(ctx context.Context, name string) (EquipmentUser, error) {
	row := q.db.QueryRow(ctx, createEquipmentUser, name)
	var i EquipmentUser
	err := row.Scan(&i.EquipmentUserID, &i.Name)
	return i, err
}

const deleteEquipmentUser = `-- name: DeleteEquipmentUser :exec
DELETE FROM equipment_user
WHERE equipment_user_id = $1
`

func (q *Queries) DeleteEquipmentUser(ctx context.Context, equipmentUserID int64) error {
	_, err := q.db.Exec(ctx, deleteEquipmentUser, equipmentUserID)
	return err
}

const listEquipmentUsers = `-- name: ListEquipmentUsers :many
SELECT equipment_user_id, name
FROM equipment_user
ORDER BY equipment_user_id
`

func (q *Queries) ListEquipmentUsers(ctx context.Context) ([]EquipmentUser, error) {
	rows, err := q.db.Query(ctx, listEquipmentUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EquipmentUser
	for rows.Next() {
		var i EquipmentUser
		if err := rows.Scan(&i.EquipmentUserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquipmentUser = `-- name: UpdateEquipmentUser :one
UPDATE equipment_user
SET name = $1
WHERE equipment_user_id = $2
RETURNING equipment_user_id, name
`

type UpdateEquipmentUserParams struct {
	Name            string `json:"name"`
	EquipmentUserID int64  `json:"equipment_user_id"`
}

func (q *Queries) UpdateEquipmentUser(ctx context.Context, arg UpdateEquipmentUserParams) (EquipmentUser, error) {
	row := q.db.QueryRow(ctx, updateEquipmentUser, arg.Name, arg.EquipmentUserID)
	var i EquipmentUser
	err := row.Scan(&i.EquipmentUserID, &i.Name)
	return i, err
}
