// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: laptops.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLaptop = `-- name: CreateLaptop :one
INSERT INTO laptop (
    computer_id, laptop_model_id,
    serial_number,
    ram_gb, ram_type, storage_gb, storage_type,
    mac_address, os_id, equipment_user_id
) VALUES (
    $1, $2,
    $3,
    $4, $5, $6, $7,
    $8, $9, $10
) RETURNING computer_id, laptop_model_id, serial_number, ram_gb, ram_type, storage_gb, storage_type, mac_address, os_id, equipment_user_id
`

type CreateLaptopParams struct {
	ComputerID      int64               `json:"computer_id"`
	LaptopModelID   int64               `json:"laptop_model_id"`
	SerialNumber    pgtype.Text         `json:"serial_number"`
	RamGb           pgtype.Int4         `json:"ram_gb"`
	RamType         NullRamTypeEnum     `json:"ram_type"`
	StorageGb       pgtype.Int4         `json:"storage_gb"`
	StorageType     NullStorageTypeEnum `json:"storage_type"`
	MacAddress      pgtype.Text         `json:"mac_address"`
	OsID            pgtype.Int8         `json:"os_id"`
	EquipmentUserID pgtype.Int8         `json:"equipment_user_id"`
}

func (q *Queries) CreateLaptop(ctx context.Context, arg CreateLaptopParams) (Laptop, error) {
	row := q.db.QueryRow(ctx, createLaptop,
		arg.ComputerID,
		arg.LaptopModelID,
		arg.SerialNumber,
		arg.RamGb,
		arg.RamType,
		arg.StorageGb,
		arg.StorageType,
		arg.MacAddress,
		arg.OsID,
		arg.EquipmentUserID,
	)
	var i Laptop
	err := row.Scan(
		&i.ComputerID,
		&i.LaptopModelID,
		&i.SerialNumber,
		&i.RamGb,
		&i.RamType,
		&i.StorageGb,
		&i.StorageType,
		&i.MacAddress,
		&i.OsID,
		&i.EquipmentUserID,
	)
	return i, err
}

const getLaptop = `-- name: GetLaptop :one
SELECT
    c.computer_id, c.hostname, c.room_id, c.observations,
    c.created_by_app_user_id, c.created_at, c.updated_at,
    l.laptop_model_id, l.serial_number, l.ram_gb, l.ram_type,
    l.storage_gb, l.storage_type, l.mac_address,
    l.os_id, l.equipment_user_id
FROM computer c
INNER JOIN laptop l ON l.computer_id = c.computer_id
WHERE c.computer_id = $1
`

type GetLaptopRow struct {
	ComputerID         int64               `json:"computer_id"`
	Hostname           string              `json:"hostname"`
	RoomID             pgtype.Int8         `json:"room_id"`
	Observations       pgtype.Text         `json:"observations"`
	CreatedByAppUserID int64               `json:"created_by_app_user_id"`
	CreatedAt          pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `json:"updated_at"`
	LaptopModelID      int64               `json:"laptop_model_id"`
	SerialNumber       pgtype.Text         `json:"serial_number"`
	RamGb              pgtype.Int4         `json:"ram_gb"`
	RamType            NullRamTypeEnum     `json:"ram_type"`
	StorageGb          pgtype.Int4         `json:"storage_gb"`
	StorageType        NullStorageTypeEnum `json:"storage_type"`
	MacAddress         pgtype.Text         `json:"mac_address"`
	OsID               pgtype.Int8         `json:"os_id"`
	EquipmentUserID    pgtype.Int8         `json:"equipment_user_id"`
}

func (q *Queries) GetLaptop(ctx context.Context, computerID int64) (GetLaptopRow, error) {
	row := q.db.QueryRow(ctx, getLaptop, computerID)
	var i GetLaptopRow
	err := row.Scan(
		&i.ComputerID,
		&i.Hostname,
		&i.RoomID,
		&i.Observations,
		&i.CreatedByAppUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LaptopModelID,
		&i.SerialNumber,
		&i.RamGb,
		&i.RamType,
		&i.StorageGb,
		&i.StorageType,
		&i.MacAddress,
		&i.OsID,
		&i.EquipmentUserID,
	)
	return i, err
}

const listLaptops = `-- name: ListLaptops :many
SELECT
    c.computer_id, c.hostname, c.room_id, c.observations,
    c.created_by_app_user_id, c.created_at, c.updated_at,
    l.laptop_model_id, l.serial_number, l.ram_gb, l.ram_type,
    l.storage_gb, l.storage_type, l.mac_address,
    l.os_id, l.equipment_user_id
FROM computer c
INNER JOIN laptop l ON l.computer_id = c.computer_id
ORDER BY c.computer_id
`

type ListLaptopsRow struct {
	ComputerID         int64               `json:"computer_id"`
	Hostname           string              `json:"hostname"`
	RoomID             pgtype.Int8         `json:"room_id"`
	Observations       pgtype.Text         `json:"observations"`
	CreatedByAppUserID int64               `json:"created_by_app_user_id"`
	CreatedAt          pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `json:"updated_at"`
	LaptopModelID      int64               `json:"laptop_model_id"`
	SerialNumber       pgtype.Text         `json:"serial_number"`
	RamGb              pgtype.Int4         `json:"ram_gb"`
	RamType            NullRamTypeEnum     `json:"ram_type"`
	StorageGb          pgtype.Int4         `json:"storage_gb"`
	StorageType        NullStorageTypeEnum `json:"storage_type"`
	MacAddress         pgtype.Text         `json:"mac_address"`
	OsID               pgtype.Int8         `json:"os_id"`
	EquipmentUserID    pgtype.Int8         `json:"equipment_user_id"`
}

func (q *Queries) ListLaptops(ctx context.Context) ([]ListLaptopsRow, error) {
	rows, err := q.db.Query(ctx, listLaptops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLaptopsRow
	for rows.Next() {
		var i ListLaptopsRow
		if err := rows.Scan(
			&i.ComputerID,
			&i.Hostname,
			&i.RoomID,
			&i.Observations,
			&i.CreatedByAppUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LaptopModelID,
			&i.SerialNumber,
			&i.RamGb,
			&i.RamType,
			&i.StorageGb,
			&i.StorageType,
			&i.MacAddress,
			&i.OsID,
			&i.EquipmentUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLaptop = `-- name: UpdateLaptop :one
UPDATE laptop
SET
    laptop_model_id   = COALESCE($1,   laptop_model_id),
    serial_number     = COALESCE($2,     serial_number),
    ram_gb            = COALESCE($3,            ram_gb),
    ram_type          = COALESCE($4,          ram_type),
    storage_gb        = COALESCE($5,        storage_gb),
    storage_type      = COALESCE($6,      storage_type),
    mac_address       = COALESCE($7,       mac_address),
    os_id             = COALESCE($8,             os_id),
    equipment_user_id = COALESCE($9, equipment_user_id)
WHERE computer_id = $10
RETURNING computer_id, laptop_model_id, serial_number, ram_gb, ram_type, storage_gb, storage_type, mac_address, os_id, equipment_user_id
`

type UpdateLaptopParams struct {
	LaptopModelID   pgtype.Int8         `json:"laptop_model_id"`
	SerialNumber    pgtype.Text         `json:"serial_number"`
	RamGb           pgtype.Int4         `json:"ram_gb"`
	RamType         NullRamTypeEnum     `json:"ram_type"`
	StorageGb       pgtype.Int4         `json:"storage_gb"`
	StorageType     NullStorageTypeEnum `json:"storage_type"`
	MacAddress      pgtype.Text         `json:"mac_address"`
	OsID            pgtype.Int8         `json:"os_id"`
	EquipmentUserID pgtype.Int8         `json:"equipment_user_id"`
	ComputerID      int64               `json:"computer_id"`
}

func (q *Queries) UpdateLaptop(ctx context.Context, arg UpdateLaptopParams) (Laptop, error) {
	row := q.db.QueryRow(ctx, updateLaptop,
		arg.LaptopModelID,
		arg.SerialNumber,
		arg.RamGb,
		arg.RamType,
		arg.StorageGb,
		arg.StorageType,
		arg.MacAddress,
		arg.OsID,
		arg.EquipmentUserID,
		arg.ComputerID,
	)
	var i Laptop
	err := row.Scan(
		&i.ComputerID,
		&i.LaptopModelID,
		&i.SerialNumber,
		&i.RamGb,
		&i.RamType,
		&i.StorageGb,
		&i.StorageType,
		&i.MacAddress,
		&i.OsID,
		&i.EquipmentUserID,
	)
	return i, err
}
