// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: laptop_models.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLaptopModel = `-- name: CreateLaptopModel :one
INSERT INTO laptop_model (
    brand_id, model_name, cpu_id,
    base_ram_gb, base_ram_type,
    base_storage_gb, base_storage_type, base_os_id
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8
) RETURNING laptop_model_id, brand_id, model_name, cpu_id, base_ram_gb, base_ram_type, base_storage_gb, base_storage_type, base_os_id
`

type CreateLaptopModelParams struct {
	BrandID         int64           `json:"brand_id"`
	ModelName       string          `json:"model_name"`
	CpuID           pgtype.Int8     `json:"cpu_id"`
	BaseRamGb       int32           `json:"base_ram_gb"`
	BaseRamType     RamTypeEnum     `json:"base_ram_type"`
	BaseStorageGb   int32           `json:"base_storage_gb"`
	BaseStorageType StorageTypeEnum `json:"base_storage_type"`
	BaseOsID        pgtype.Int8     `json:"base_os_id"`
}

func (q *Queries) CreateLaptopModel(ctx context.Context, arg CreateLaptopModelParams) (LaptopModel, error) {
	row := q.db.QueryRow(ctx, createLaptopModel,
		arg.BrandID,
		arg.ModelName,
		arg.CpuID,
		arg.BaseRamGb,
		arg.BaseRamType,
		arg.BaseStorageGb,
		arg.BaseStorageType,
		arg.BaseOsID,
	)
	var i LaptopModel
	err := row.Scan(
		&i.LaptopModelID,
		&i.BrandID,
		&i.ModelName,
		&i.CpuID,
		&i.BaseRamGb,
		&i.BaseRamType,
		&i.BaseStorageGb,
		&i.BaseStorageType,
		&i.BaseOsID,
	)
	return i, err
}

const deleteLaptopModel = `-- name: DeleteLaptopModel :exec
DELETE FROM laptop_model WHERE laptop_model_id = $1
`

func (q *Queries) DeleteLaptopModel(ctx context.Context, laptopModelID int64) error {
	_, err := q.db.Exec(ctx, deleteLaptopModel, laptopModelID)
	return err
}

const getLaptopModel = `-- name: GetLaptopModel :one
SELECT lm.laptop_model_id, lm.brand_id, lm.model_name, lm.cpu_id, lm.base_ram_gb, lm.base_ram_type, lm.base_storage_gb, lm.base_storage_type, lm.base_os_id, b.name AS brand_name
FROM laptop_model lm
JOIN brand b ON b.brand_id = lm.brand_id
WHERE lm.laptop_model_id = $1
`

type GetLaptopModelRow struct {
	LaptopModelID   int64           `json:"laptop_model_id"`
	BrandID         int64           `json:"brand_id"`
	ModelName       string          `json:"model_name"`
	CpuID           pgtype.Int8     `json:"cpu_id"`
	BaseRamGb       int32           `json:"base_ram_gb"`
	BaseRamType     RamTypeEnum     `json:"base_ram_type"`
	BaseStorageGb   int32           `json:"base_storage_gb"`
	BaseStorageType StorageTypeEnum `json:"base_storage_type"`
	BaseOsID        pgtype.Int8     `json:"base_os_id"`
	BrandName       string          `json:"brand_name"`
}

func (q *Queries) GetLaptopModel(ctx context.Context, laptopModelID int64) (GetLaptopModelRow, error) {
	row := q.db.QueryRow(ctx, getLaptopModel, laptopModelID)
	var i GetLaptopModelRow
	err := row.Scan(
		&i.LaptopModelID,
		&i.BrandID,
		&i.ModelName,
		&i.CpuID,
		&i.BaseRamGb,
		&i.BaseRamType,
		&i.BaseStorageGb,
		&i.BaseStorageType,
		&i.BaseOsID,
		&i.BrandName,
	)
	return i, err
}

const listLaptopModels = `-- name: ListLaptopModels :many
SELECT lm.laptop_model_id, lm.brand_id, lm.model_name, lm.cpu_id, lm.base_ram_gb, lm.base_ram_type, lm.base_storage_gb, lm.base_storage_type, lm.base_os_id, b.name AS brand_name
FROM laptop_model lm
JOIN brand b ON b.brand_id = lm.brand_id
ORDER BY b.name, lm.model_name
`

type ListLaptopModelsRow struct {
	LaptopModelID   int64           `json:"laptop_model_id"`
	BrandID         int64           `json:"brand_id"`
	ModelName       string          `json:"model_name"`
	CpuID           pgtype.Int8     `json:"cpu_id"`
	BaseRamGb       int32           `json:"base_ram_gb"`
	BaseRamType     RamTypeEnum     `json:"base_ram_type"`
	BaseStorageGb   int32           `json:"base_storage_gb"`
	BaseStorageType StorageTypeEnum `json:"base_storage_type"`
	BaseOsID        pgtype.Int8     `json:"base_os_id"`
	BrandName       string          `json:"brand_name"`
}

func (q *Queries) ListLaptopModels(ctx context.Context) ([]ListLaptopModelsRow, error) {
	rows, err := q.db.Query(ctx, listLaptopModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLaptopModelsRow
	for rows.Next() {
		var i ListLaptopModelsRow
		if err := rows.Scan(
			&i.LaptopModelID,
			&i.BrandID,
			&i.ModelName,
			&i.CpuID,
			&i.BaseRamGb,
			&i.BaseRamType,
			&i.BaseStorageGb,
			&i.BaseStorageType,
			&i.BaseOsID,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLaptopModel = `-- name: UpdateLaptopModel :one
UPDATE laptop_model
SET
    brand_id          = COALESCE($1,          brand_id),
    model_name        = COALESCE($2,        model_name),
    cpu_id            = COALESCE($3,            cpu_id),
    base_ram_gb       = COALESCE($4,       base_ram_gb),
    base_ram_type     = COALESCE($5,     base_ram_type),
    base_storage_gb   = COALESCE($6,   base_storage_gb),
    base_storage_type = COALESCE($7, base_storage_type),
    base_os_id        = COALESCE($8,        base_os_id)
WHERE laptop_model_id = $9
RETURNING laptop_model_id, brand_id, model_name, cpu_id, base_ram_gb, base_ram_type, base_storage_gb, base_storage_type, base_os_id
`

type UpdateLaptopModelParams struct {
	BrandID         pgtype.Int8         `json:"brand_id"`
	ModelName       pgtype.Text         `json:"model_name"`
	CpuID           pgtype.Int8         `json:"cpu_id"`
	BaseRamGb       pgtype.Int4         `json:"base_ram_gb"`
	BaseRamType     NullRamTypeEnum     `json:"base_ram_type"`
	BaseStorageGb   pgtype.Int4         `json:"base_storage_gb"`
	BaseStorageType NullStorageTypeEnum `json:"base_storage_type"`
	BaseOsID        pgtype.Int8         `json:"base_os_id"`
	LaptopModelID   int64               `json:"laptop_model_id"`
}

func (q *Queries) UpdateLaptopModel(ctx context.Context, arg UpdateLaptopModelParams) (LaptopModel, error) {
	row := q.db.QueryRow(ctx, updateLaptopModel,
		arg.BrandID,
		arg.ModelName,
		arg.CpuID,
		arg.BaseRamGb,
		arg.BaseRamType,
		arg.BaseStorageGb,
		arg.BaseStorageType,
		arg.BaseOsID,
		arg.LaptopModelID,
	)
	var i LaptopModel
	err := row.Scan(
		&i.LaptopModelID,
		&i.BrandID,
		&i.ModelName,
		&i.CpuID,
		&i.BaseRamGb,
		&i.BaseRamType,
		&i.BaseStorageGb,
		&i.BaseStorageType,
		&i.BaseOsID,
	)
	return i, err
}
