// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEventEnum string

const (
	AuditEventEnumUpdated AuditEventEnum = "updated"
	AuditEventEnumDeleted AuditEventEnum = "deleted"
)

func (e *AuditEventEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditEventEnum(s)
	case string:
		*e = AuditEventEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditEventEnum: %T", src)
	}
	return nil
}

type NullAuditEventEnum struct {
	AuditEventEnum AuditEventEnum `json:"audit_event_enum"`
	Valid          bool           `json:"valid"` // Valid is true if AuditEventEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditEventEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AuditEventEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditEventEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditEventEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditEventEnum), nil
}

type ComputerTypeEnum string

const (
	ComputerTypeEnumDesktop ComputerTypeEnum = "desktop"
	ComputerTypeEnumLaptop  ComputerTypeEnum = "laptop"
)

func (e *ComputerTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComputerTypeEnum(s)
	case string:
		*e = ComputerTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ComputerTypeEnum: %T", src)
	}
	return nil
}

type NullComputerTypeEnum struct {
	ComputerTypeEnum ComputerTypeEnum `json:"computer_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if ComputerTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComputerTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ComputerTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComputerTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComputerTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComputerTypeEnum), nil
}

type RamTypeEnum string

const (
	RamTypeEnumDDR3 RamTypeEnum = "DDR3"
	RamTypeEnumDDR4 RamTypeEnum = "DDR4"
	RamTypeEnumDDR5 RamTypeEnum = "DDR5"
	RamTypeEnumNone RamTypeEnum = "None"
)

func (e *RamTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RamTypeEnum(s)
	case string:
		*e = RamTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RamTypeEnum: %T", src)
	}
	return nil
}

type NullRamTypeEnum struct {
	RamTypeEnum RamTypeEnum `json:"ram_type_enum"`
	Valid       bool        `json:"valid"` // Valid is true if RamTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRamTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RamTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RamTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRamTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RamTypeEnum), nil
}

type StorageTypeEnum string

const (
	StorageTypeEnumHDD  StorageTypeEnum = "HDD"
	StorageTypeEnumSSD  StorageTypeEnum = "SSD"
	StorageTypeEnumNVMe StorageTypeEnum = "NVMe"
	StorageTypeEnumNone StorageTypeEnum = "None"
)

func (e *StorageTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StorageTypeEnum(s)
	case string:
		*e = StorageTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for StorageTypeEnum: %T", src)
	}
	return nil
}

type NullStorageTypeEnum struct {
	StorageTypeEnum StorageTypeEnum `json:"storage_type_enum"`
	Valid           bool            `json:"valid"` // Valid is true if StorageTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStorageTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.StorageTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StorageTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStorageTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StorageTypeEnum), nil
}

type AppUser struct {
	AppUserID    int64  `json:"app_user_id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	CanCreate    bool   `json:"can_create"`
	CanUpdate    bool   `json:"can_update"`
	CanDelete    bool   `json:"can_delete"`
	IsMeta       bool   `json:"is_meta"`
}

type Center struct {
	CenterID int64  `json:"center_id"`
	Name     string `json:"name"`
}

type Computer struct {
	ComputerID         int64              `json:"computer_id"`
	Hostname           string             `json:"hostname"`
	CpuID              pgtype.Int8        `json:"cpu_id"`
	RamGb              int32              `json:"ram_gb"`
	RamType            RamTypeEnum        `json:"ram_type"`
	StorageGb          int32              `json:"storage_gb"`
	StorageType        StorageTypeEnum    `json:"storage_type"`
	ComputerType       ComputerTypeEnum   `json:"computer_type"`
	Observations       pgtype.Text        `json:"observations"`
	EquipmentUserID    pgtype.Int8        `json:"equipment_user_id"`
	RoomID             pgtype.Int8        `json:"room_id"`
	MacAddress         pgtype.Text        `json:"mac_address"`
	CreatedByAppUserID int64              `json:"created_by_app_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ComputerAudit struct {
	AuditID            int64              `json:"audit_id"`
	EventType          AuditEventEnum     `json:"event_type"`
	ComputerID         int64              `json:"computer_id"`
	OldValues          json.RawMessage    `json:"old_values"`
	NewValues          []byte             `json:"new_values"`
	ChangedByAppUserID int64              `json:"changed_by_app_user_id"`
	ChangedAt          pgtype.Timestamptz `json:"changed_at"`
}

type ComputerO struct {
	ComputerID int64 `json:"computer_id"`
	OsID       int64 `json:"os_id"`
}

type Cpu struct {
	CpuID          int64       `json:"cpu_id"`
	ModelName      pgtype.Text `json:"model_name"`
	BenchmarkScore pgtype.Int4 `json:"benchmark_score"`
}

type EquipmentUser struct {
	EquipmentUserID int64  `json:"equipment_user_id"`
	Name            string `json:"name"`
}

type O struct {
	OsID int64  `json:"os_id"`
	Name string `json:"name"`
}

type Room struct {
	RoomID   int64  `json:"room_id"`
	CenterID int64  `json:"center_id"`
	Name     string `json:"name"`
}
