// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEventEnum string

const (
	AuditEventEnumCreated AuditEventEnum = "created"
	AuditEventEnumUpdated AuditEventEnum = "updated"
	AuditEventEnumDeleted AuditEventEnum = "deleted"
)

func (e *AuditEventEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditEventEnum(s)
	case string:
		*e = AuditEventEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditEventEnum: %T", src)
	}
	return nil
}

type NullAuditEventEnum struct {
	AuditEventEnum AuditEventEnum `json:"audit_event_enum"`
	Valid          bool           `json:"valid"` // Valid is true if AuditEventEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditEventEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AuditEventEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditEventEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditEventEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditEventEnum), nil
}

type ConnectionTypeEnum string

const (
	ConnectionTypeEnumEthernet ConnectionTypeEnum = "ethernet"
	ConnectionTypeEnumWifi     ConnectionTypeEnum = "wifi"
)

func (e *ConnectionTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConnectionTypeEnum(s)
	case string:
		*e = ConnectionTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ConnectionTypeEnum: %T", src)
	}
	return nil
}

type NullConnectionTypeEnum struct {
	ConnectionTypeEnum ConnectionTypeEnum `json:"connection_type_enum"`
	Valid              bool               `json:"valid"` // Valid is true if ConnectionTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConnectionTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ConnectionTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConnectionTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConnectionTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConnectionTypeEnum), nil
}

type DeviceStatusEnum string

const (
	DeviceStatusEnumActiu DeviceStatusEnum = "actiu"
	DeviceStatusEnumBaixa DeviceStatusEnum = "baixa"
)

func (e *DeviceStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceStatusEnum(s)
	case string:
		*e = DeviceStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceStatusEnum: %T", src)
	}
	return nil
}

type NullDeviceStatusEnum struct {
	DeviceStatusEnum DeviceStatusEnum `json:"device_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if DeviceStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceStatusEnum), nil
}

type PrintColorEnum string

const (
	PrintColorEnumColor PrintColorEnum = "Color"
	PrintColorEnumBN    PrintColorEnum = "BN"
)

func (e *PrintColorEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrintColorEnum(s)
	case string:
		*e = PrintColorEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PrintColorEnum: %T", src)
	}
	return nil
}

type NullPrintColorEnum struct {
	PrintColorEnum PrintColorEnum `json:"print_color_enum"`
	Valid          bool           `json:"valid"` // Valid is true if PrintColorEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrintColorEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PrintColorEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrintColorEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrintColorEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrintColorEnum), nil
}

type PrinterTypeEnum string

const (
	PrinterTypeEnumToner   PrinterTypeEnum = "toner"
	PrinterTypeEnumInk     PrinterTypeEnum = "ink"
	PrinterTypeEnumManaged PrinterTypeEnum = "managed"
)

func (e *PrinterTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrinterTypeEnum(s)
	case string:
		*e = PrinterTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PrinterTypeEnum: %T", src)
	}
	return nil
}

type NullPrinterTypeEnum struct {
	PrinterTypeEnum PrinterTypeEnum `json:"printer_type_enum"`
	Valid           bool            `json:"valid"` // Valid is true if PrinterTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrinterTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PrinterTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrinterTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrinterTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrinterTypeEnum), nil
}

type RamTypeEnum string

const (
	RamTypeEnumDDR3 RamTypeEnum = "DDR3"
	RamTypeEnumDDR4 RamTypeEnum = "DDR4"
	RamTypeEnumDDR5 RamTypeEnum = "DDR5"
	RamTypeEnumNone RamTypeEnum = "None"
)

func (e *RamTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RamTypeEnum(s)
	case string:
		*e = RamTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RamTypeEnum: %T", src)
	}
	return nil
}

type NullRamTypeEnum struct {
	RamTypeEnum RamTypeEnum `json:"ram_type_enum"`
	Valid       bool        `json:"valid"` // Valid is true if RamTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRamTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RamTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RamTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRamTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RamTypeEnum), nil
}

type ShiftEnum string

const (
	ShiftEnumMorning   ShiftEnum = "morning"
	ShiftEnumAfternoon ShiftEnum = "afternoon"
)

func (e *ShiftEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShiftEnum(s)
	case string:
		*e = ShiftEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ShiftEnum: %T", src)
	}
	return nil
}

type NullShiftEnum struct {
	ShiftEnum ShiftEnum `json:"shift_enum"`
	Valid     bool      `json:"valid"` // Valid is true if ShiftEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShiftEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ShiftEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShiftEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShiftEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShiftEnum), nil
}

type StorageTypeEnum string

const (
	StorageTypeEnumHDD  StorageTypeEnum = "HDD"
	StorageTypeEnumSSD  StorageTypeEnum = "SSD"
	StorageTypeEnumNVMe StorageTypeEnum = "NVMe"
	StorageTypeEnumNone StorageTypeEnum = "None"
)

func (e *StorageTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StorageTypeEnum(s)
	case string:
		*e = StorageTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for StorageTypeEnum: %T", src)
	}
	return nil
}

type NullStorageTypeEnum struct {
	StorageTypeEnum StorageTypeEnum `json:"storage_type_enum"`
	Valid           bool            `json:"valid"` // Valid is true if StorageTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStorageTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.StorageTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StorageTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStorageTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StorageTypeEnum), nil
}

type AppUser struct {
	AppUserID    int64  `json:"app_user_id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	RoleID       string `json:"role_id"`
}

type AuditLog struct {
	AuditID            int64              `json:"audit_id"`
	TableName          string             `json:"table_name"`
	RecordID           int64              `json:"record_id"`
	EventType          AuditEventEnum     `json:"event_type"`
	OldValues          []byte             `json:"old_values"`
	NewValues          []byte             `json:"new_values"`
	ChangedByAppUserID int64              `json:"changed_by_app_user_id"`
	ChangedByUsername  string             `json:"changed_by_username"`
	ChangedAt          pgtype.Timestamptz `json:"changed_at"`
}

type Brand struct {
	BrandID int64  `json:"brand_id"`
	Name    string `json:"name"`
}

type Center struct {
	CenterID int64  `json:"center_id"`
	Name     string `json:"name"`
}

type Computer struct {
	ComputerID         int64              `json:"computer_id"`
	Hostname           string             `json:"hostname"`
	RoomID             pgtype.Int8        `json:"room_id"`
	Observations       pgtype.Text        `json:"observations"`
	CreatedByAppUserID int64              `json:"created_by_app_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Cpu struct {
	CpuID          int64       `json:"cpu_id"`
	ModelName      string      `json:"model_name"`
	BenchmarkScore pgtype.Int4 `json:"benchmark_score"`
}

type Cycle struct {
	CycleID int64  `json:"cycle_id"`
	Name    string `json:"name"`
}

type Desktop struct {
	ComputerID        int64                  `json:"computer_id"`
	DesktopModelID    pgtype.Int8            `json:"desktop_model_id"`
	CpuID             pgtype.Int8            `json:"cpu_id"`
	RamGb             pgtype.Int4            `json:"ram_gb"`
	RamType           NullRamTypeEnum        `json:"ram_type"`
	StorageGb         pgtype.Int4            `json:"storage_gb"`
	StorageType       NullStorageTypeEnum    `json:"storage_type"`
	OsID              pgtype.Int8            `json:"os_id"`
	EquipmentUserID   pgtype.Int8            `json:"equipment_user_id"`
	HasWifiCard       bool                   `json:"has_wifi_card"`
	MacAddress        pgtype.Text            `json:"mac_address"`
	NetworkConnection NullConnectionTypeEnum `json:"network_connection"`
}

type DesktopModel struct {
	DesktopModelID  int64           `json:"desktop_model_id"`
	BrandID         int64           `json:"brand_id"`
	ModelName       string          `json:"model_name"`
	CpuID           pgtype.Int8     `json:"cpu_id"`
	BaseRamGb       int32           `json:"base_ram_gb"`
	BaseRamType     RamTypeEnum     `json:"base_ram_type"`
	BaseStorageGb   int32           `json:"base_storage_gb"`
	BaseStorageType StorageTypeEnum `json:"base_storage_type"`
	BaseOsID        pgtype.Int8     `json:"base_os_id"`
}

type EquipmentUser struct {
	EquipmentUserID int64  `json:"equipment_user_id"`
	Name            string `json:"name"`
}

type Laptop struct {
	ComputerID      int64               `json:"computer_id"`
	LaptopModelID   int64               `json:"laptop_model_id"`
	SerialNumber    pgtype.Text         `json:"serial_number"`
	RamGb           pgtype.Int4         `json:"ram_gb"`
	RamType         NullRamTypeEnum     `json:"ram_type"`
	StorageGb       pgtype.Int4         `json:"storage_gb"`
	StorageType     NullStorageTypeEnum `json:"storage_type"`
	MacAddress      pgtype.Text         `json:"mac_address"`
	OsID            pgtype.Int8         `json:"os_id"`
	EquipmentUserID pgtype.Int8         `json:"equipment_user_id"`
}

type LaptopModel struct {
	LaptopModelID   int64           `json:"laptop_model_id"`
	BrandID         int64           `json:"brand_id"`
	ModelName       string          `json:"model_name"`
	CpuID           pgtype.Int8     `json:"cpu_id"`
	BaseRamGb       int32           `json:"base_ram_gb"`
	BaseRamType     RamTypeEnum     `json:"base_ram_type"`
	BaseStorageGb   int32           `json:"base_storage_gb"`
	BaseStorageType StorageTypeEnum `json:"base_storage_type"`
	BaseOsID        pgtype.Int8     `json:"base_os_id"`
}

type LaptopStudentAssignment struct {
	AssignmentID int64  `json:"assignment_id"`
	ComputerID   int64  `json:"computer_id"`
	StudentID    int64  `json:"student_id"`
	ClassID      int64  `json:"class_id"`
	AcademicYear string `json:"academic_year"`
}

type O struct {
	OsID int64  `json:"os_id"`
	Name string `json:"name"`
}

type Printer struct {
	PrinterID            int64              `json:"printer_id"`
	PrinterModelID       int64              `json:"printer_model_id"`
	Status               DeviceStatusEnum   `json:"status"`
	HasNetworkCapability bool               `json:"has_network_capability"`
	UsesNetwork          bool               `json:"uses_network"`
	IpAddress            pgtype.Text        `json:"ip_address"`
	RoomID               pgtype.Int8        `json:"room_id"`
	EquipmentUserID      pgtype.Int8        `json:"equipment_user_id"`
	Observations         pgtype.Text        `json:"observations"`
	CreatedByAppUserID   int64              `json:"created_by_app_user_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PrinterModel struct {
	PrinterModelID int64           `json:"printer_model_id"`
	BrandID        int64           `json:"brand_id"`
	ModelName      string          `json:"model_name"`
	PrinterType    PrinterTypeEnum `json:"printer_type"`
	PrintColor     PrintColorEnum  `json:"print_color"`
}

type PrinterModelSupply struct {
	PrinterModelID  int64 `json:"printer_model_id"`
	PrinterSupplyID int64 `json:"printer_supply_id"`
}

type PrinterSupply struct {
	PrinterSupplyID int64           `json:"printer_supply_id"`
	Name            string          `json:"name"`
	SupplyType      PrinterTypeEnum `json:"supply_type"`
}

type Projector struct {
	ProjectorID        int64              `json:"projector_id"`
	ProjectorModelID   int64              `json:"projector_model_id"`
	SerialNumber       pgtype.Text        `json:"serial_number"`
	Status             DeviceStatusEnum   `json:"status"`
	RoomID             pgtype.Int8        `json:"room_id"`
	EquipmentUserID    pgtype.Int8        `json:"equipment_user_id"`
	Observations       pgtype.Text        `json:"observations"`
	CreatedByAppUserID int64              `json:"created_by_app_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ProjectorModel struct {
	ProjectorModelID int64  `json:"projector_model_id"`
	BrandID          int64  `json:"brand_id"`
	ModelName        string `json:"model_name"`
}

type Role struct {
	RoleID      string `json:"role_id"`
	Description string `json:"description"`
}

type Room struct {
	RoomID   int64  `json:"room_id"`
	CenterID int64  `json:"center_id"`
	Name     string `json:"name"`
}

type SchoolClass struct {
	ClassID        int64       `json:"class_id"`
	CycleID        int64       `json:"cycle_id"`
	Course         int16       `json:"course"`
	ClassLabel     string      `json:"class_label"`
	Shift          ShiftEnum   `json:"shift"`
	TutorAppUserID pgtype.Int8 `json:"tutor_app_user_id"`
}

type Student struct {
	StudentID int64  `json:"student_id"`
	FullName  string `json:"full_name"`
	ClassID   int64  `json:"class_id"`
}
