// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operating_systems.sql

package dbsqlc

import (
	"context"
)

const createOS = `-- name: CreateOS :one
INSERT INTO os (name)
VALUES ($1)
RETURNING os_id, name
`

func (q *Queries) CreateOS(ctx context.Context, name string) (O, error) {
	row := q.db.QueryRow(ctx, createOS, name)
	var i O
	err := row.Scan(&i.OsID, &i.Name)
	return i, err
}

const deleteOS = `-- name: DeleteOS :exec
DELETE FROM os
WHERE os_id = $1
`

func (q *Queries) DeleteOS(ctx context.Context, osID int64) error {
	_, err := q.db.Exec(ctx, deleteOS, osID)
	return err
}

const listOS = `-- name: ListOS :many
SELECT os_id, name
FROM os
ORDER BY os_id
`

func (q *Queries) ListOS(ctx context.Context) ([]O, error) {
	rows, err := q.db.Query(ctx, listOS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []O
	for rows.Next() {
		var i O
		if err := rows.Scan(&i.OsID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOS = `-- name: UpdateOS :one
UPDATE os
SET name = $1
WHERE os_id = $2
RETURNING os_id, name
`

type UpdateOSParams struct {
	Name string `json:"name"`
	OsID int64  `json:"os_id"`
}

func (q *Queries) UpdateOS(ctx context.Context, arg UpdateOSParams) (O, error) {
	row := q.db.QueryRow(ctx, updateOS, arg.Name, arg.OsID)
	var i O
	err := row.Scan(&i.OsID, &i.Name)
	return i, err
}
