// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: printers.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPrinterModelSupply = `-- name: AddPrinterModelSupply :exec
INSERT INTO printer_model_supply (printer_model_id, printer_supply_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPrinterModelSupplyParams struct {
	PrinterModelID  int64 `json:"printer_model_id"`
	PrinterSupplyID int64 `json:"printer_supply_id"`
}

func (q *Queries) AddPrinterModelSupply(ctx context.Context, arg AddPrinterModelSupplyParams) error {
	_, err := q.db.Exec(ctx, addPrinterModelSupply, arg.PrinterModelID, arg.PrinterSupplyID)
	return err
}

const createPrinter = `-- name: CreatePrinter :one
INSERT INTO printer (
    printer_model_id,
    status,
    has_network_capability,
    uses_network,
    ip_address,
    room_id,
    equipment_user_id,
    observations,
    created_by_app_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
) RETURNING printer_id, printer_model_id, status, has_network_capability, uses_network, ip_address, room_id, equipment_user_id, observations, created_by_app_user_id, created_at, updated_at
`

type CreatePrinterParams struct {
	PrinterModelID       int64            `json:"printer_model_id"`
	Status               DeviceStatusEnum `json:"status"`
	HasNetworkCapability bool             `json:"has_network_capability"`
	UsesNetwork          bool             `json:"uses_network"`
	IpAddress            pgtype.Text      `json:"ip_address"`
	RoomID               pgtype.Int8      `json:"room_id"`
	EquipmentUserID      pgtype.Int8      `json:"equipment_user_id"`
	Observations         pgtype.Text      `json:"observations"`
	CreatedByAppUserID   int64            `json:"created_by_app_user_id"`
}

func (q *Queries) CreatePrinter(ctx context.Context, arg CreatePrinterParams) (Printer, error) {
	row := q.db.QueryRow(ctx, createPrinter,
		arg.PrinterModelID,
		arg.Status,
		arg.HasNetworkCapability,
		arg.UsesNetwork,
		arg.IpAddress,
		arg.RoomID,
		arg.EquipmentUserID,
		arg.Observations,
		arg.CreatedByAppUserID,
	)
	var i Printer
	err := row.Scan(
		&i.PrinterID,
		&i.PrinterModelID,
		&i.Status,
		&i.HasNetworkCapability,
		&i.UsesNetwork,
		&i.IpAddress,
		&i.RoomID,
		&i.EquipmentUserID,
		&i.Observations,
		&i.CreatedByAppUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPrinterModel = `-- name: CreatePrinterModel :one
INSERT INTO printer_model (brand_id, model_name, printer_type, print_color)
VALUES ($1, $2, $3, $4)
RETURNING printer_model_id, brand_id, model_name, printer_type, print_color
`

type CreatePrinterModelParams struct {
	BrandID     int64           `json:"brand_id"`
	ModelName   string          `json:"model_name"`
	PrinterType PrinterTypeEnum `json:"printer_type"`
	PrintColor  PrintColorEnum  `json:"print_color"`
}

func (q *Queries) CreatePrinterModel(ctx context.Context, arg CreatePrinterModelParams) (PrinterModel, error) {
	row := q.db.QueryRow(ctx, createPrinterModel,
		arg.BrandID,
		arg.ModelName,
		arg.PrinterType,
		arg.PrintColor,
	)
	var i PrinterModel
	err := row.Scan(
		&i.PrinterModelID,
		&i.BrandID,
		&i.ModelName,
		&i.PrinterType,
		&i.PrintColor,
	)
	return i, err
}

const createPrinterSupply = `-- name: CreatePrinterSupply :one
INSERT INTO printer_supply (name, supply_type)
VALUES ($1, $2)
RETURNING printer_supply_id, name, supply_type
`

type CreatePrinterSupplyParams struct {
	Name       string          `json:"name"`
	SupplyType PrinterTypeEnum `json:"supply_type"`
}

func (q *Queries) CreatePrinterSupply(ctx context.Context, arg CreatePrinterSupplyParams) (PrinterSupply, error) {
	row := q.db.QueryRow(ctx, createPrinterSupply, arg.Name, arg.SupplyType)
	var i PrinterSupply
	err := row.Scan(&i.PrinterSupplyID, &i.Name, &i.SupplyType)
	return i, err
}

const deletePrinter = `-- name: DeletePrinter :exec
DELETE FROM printer WHERE printer_id = $1
`

func (q *Queries) DeletePrinter(ctx context.Context, printerID int64) error {
	_, err := q.db.Exec(ctx, deletePrinter, printerID)
	return err
}

const deletePrinterModel = `-- name: DeletePrinterModel :exec
DELETE FROM printer_model WHERE printer_model_id = $1
`

func (q *Queries) DeletePrinterModel(ctx context.Context, printerModelID int64) error {
	_, err := q.db.Exec(ctx, deletePrinterModel, printerModelID)
	return err
}

const deletePrinterSupply = `-- name: DeletePrinterSupply :exec
DELETE FROM printer_supply WHERE printer_supply_id = $1
`

func (q *Queries) DeletePrinterSupply(ctx context.Context, printerSupplyID int64) error {
	_, err := q.db.Exec(ctx, deletePrinterSupply, printerSupplyID)
	return err
}

const getPrinter = `-- name: GetPrinter :one
SELECT
    p.printer_id, p.status,
    p.has_network_capability, p.uses_network, p.ip_address,
    p.room_id, p.equipment_user_id, p.observations,
    p.created_by_app_user_id, p.created_at, p.updated_at,
    p.printer_model_id,
    pm.model_name,
    pm.printer_type,
    pm.print_color,
    b.brand_id,
    b.name AS brand_name,
    r.name AS room_name,
    eu.name AS equipment_user_name
FROM printer p
JOIN printer_model pm ON pm.printer_model_id = p.printer_model_id
JOIN brand b ON b.brand_id = pm.brand_id
LEFT JOIN room r ON r.room_id = p.room_id
LEFT JOIN equipment_user eu ON eu.equipment_user_id = p.equipment_user_id
WHERE p.printer_id = $1
`

type GetPrinterRow struct {
	PrinterID            int64              `json:"printer_id"`
	Status               DeviceStatusEnum   `json:"status"`
	HasNetworkCapability bool               `json:"has_network_capability"`
	UsesNetwork          bool               `json:"uses_network"`
	IpAddress            pgtype.Text        `json:"ip_address"`
	RoomID               pgtype.Int8        `json:"room_id"`
	EquipmentUserID      pgtype.Int8        `json:"equipment_user_id"`
	Observations         pgtype.Text        `json:"observations"`
	CreatedByAppUserID   int64              `json:"created_by_app_user_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	PrinterModelID       int64              `json:"printer_model_id"`
	ModelName            string             `json:"model_name"`
	PrinterType          PrinterTypeEnum    `json:"printer_type"`
	PrintColor           PrintColorEnum     `json:"print_color"`
	BrandID              int64              `json:"brand_id"`
	BrandName            string             `json:"brand_name"`
	RoomName             pgtype.Text        `json:"room_name"`
	EquipmentUserName    pgtype.Text        `json:"equipment_user_name"`
}

func (q *Queries) GetPrinter(ctx context.Context, printerID int64) (GetPrinterRow, error) {
	row := q.db.QueryRow(ctx, getPrinter, printerID)
	var i GetPrinterRow
	err := row.Scan(
		&i.PrinterID,
		&i.Status,
		&i.HasNetworkCapability,
		&i.UsesNetwork,
		&i.IpAddress,
		&i.RoomID,
		&i.EquipmentUserID,
		&i.Observations,
		&i.CreatedByAppUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrinterModelID,
		&i.ModelName,
		&i.PrinterType,
		&i.PrintColor,
		&i.BrandID,
		&i.BrandName,
		&i.RoomName,
		&i.EquipmentUserName,
	)
	return i, err
}

const getPrinterModel = `-- name: GetPrinterModel :one
SELECT pm.printer_model_id, pm.brand_id, pm.model_name, pm.printer_type, pm.print_color, b.name AS brand_name
FROM printer_model pm
JOIN brand b ON b.brand_id = pm.brand_id
WHERE pm.printer_model_id = $1
`

type GetPrinterModelRow struct {
	PrinterModelID int64           `json:"printer_model_id"`
	BrandID        int64           `json:"brand_id"`
	ModelName      string          `json:"model_name"`
	PrinterType    PrinterTypeEnum `json:"printer_type"`
	PrintColor     PrintColorEnum  `json:"print_color"`
	BrandName      string          `json:"brand_name"`
}

func (q *Queries) GetPrinterModel(ctx context.Context, printerModelID int64) (GetPrinterModelRow, error) {
	row := q.db.QueryRow(ctx, getPrinterModel, printerModelID)
	var i GetPrinterModelRow
	err := row.Scan(
		&i.PrinterModelID,
		&i.BrandID,
		&i.ModelName,
		&i.PrinterType,
		&i.PrintColor,
		&i.BrandName,
	)
	return i, err
}

const getPrinterSupply = `-- name: GetPrinterSupply :one
SELECT printer_supply_id, name, supply_type FROM printer_supply WHERE printer_supply_id = $1
`

func (q *Queries) GetPrinterSupply(ctx context.Context, printerSupplyID int64) (PrinterSupply, error) {
	row := q.db.QueryRow(ctx, getPrinterSupply, printerSupplyID)
	var i PrinterSupply
	err := row.Scan(&i.PrinterSupplyID, &i.Name, &i.SupplyType)
	return i, err
}

const listPrinterModels = `-- name: ListPrinterModels :many

SELECT pm.printer_model_id, pm.brand_id, pm.model_name, pm.printer_type, pm.print_color, b.name AS brand_name
FROM printer_model pm
JOIN brand b ON b.brand_id = pm.brand_id
ORDER BY b.name, pm.model_name
`

type ListPrinterModelsRow struct {
	PrinterModelID int64           `json:"printer_model_id"`
	BrandID        int64           `json:"brand_id"`
	ModelName      string          `json:"model_name"`
	PrinterType    PrinterTypeEnum `json:"printer_type"`
	PrintColor     PrintColorEnum  `json:"print_color"`
	BrandName      string          `json:"brand_name"`
}

// ============================================================
// PRINTER MODELS
// ============================================================
func (q *Queries) ListPrinterModels(ctx context.Context) ([]ListPrinterModelsRow, error) {
	rows, err := q.db.Query(ctx, listPrinterModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrinterModelsRow
	for rows.Next() {
		var i ListPrinterModelsRow
		if err := rows.Scan(
			&i.PrinterModelID,
			&i.BrandID,
			&i.ModelName,
			&i.PrinterType,
			&i.PrintColor,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrinterSupplies = `-- name: ListPrinterSupplies :many

SELECT printer_supply_id, name, supply_type FROM printer_supply ORDER BY name
`

// ============================================================
// PRINTER SUPPLIES (consumibles)
// ============================================================
func (q *Queries) ListPrinterSupplies(ctx context.Context) ([]PrinterSupply, error) {
	rows, err := q.db.Query(ctx, listPrinterSupplies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrinterSupply
	for rows.Next() {
		var i PrinterSupply
		if err := rows.Scan(&i.PrinterSupplyID, &i.Name, &i.SupplyType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrinters = `-- name: ListPrinters :many

SELECT
    p.printer_id, p.status,
    p.has_network_capability, p.uses_network, p.ip_address,
    p.room_id, p.equipment_user_id, p.observations,
    p.created_by_app_user_id, p.created_at, p.updated_at,
    p.printer_model_id,
    pm.model_name,
    pm.printer_type,
    pm.print_color,
    b.brand_id,
    b.name AS brand_name,
    r.name AS room_name,
    eu.name AS equipment_user_name
FROM printer p
JOIN printer_model pm ON pm.printer_model_id = p.printer_model_id
JOIN brand b ON b.brand_id = pm.brand_id
LEFT JOIN room r ON r.room_id = p.room_id
LEFT JOIN equipment_user eu ON eu.equipment_user_id = p.equipment_user_id
ORDER BY p.printer_id
`

type ListPrintersRow struct {
	PrinterID            int64              `json:"printer_id"`
	Status               DeviceStatusEnum   `json:"status"`
	HasNetworkCapability bool               `json:"has_network_capability"`
	UsesNetwork          bool               `json:"uses_network"`
	IpAddress            pgtype.Text        `json:"ip_address"`
	RoomID               pgtype.Int8        `json:"room_id"`
	EquipmentUserID      pgtype.Int8        `json:"equipment_user_id"`
	Observations         pgtype.Text        `json:"observations"`
	CreatedByAppUserID   int64              `json:"created_by_app_user_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	PrinterModelID       int64              `json:"printer_model_id"`
	ModelName            string             `json:"model_name"`
	PrinterType          PrinterTypeEnum    `json:"printer_type"`
	PrintColor           PrintColorEnum     `json:"print_color"`
	BrandID              int64              `json:"brand_id"`
	BrandName            string             `json:"brand_name"`
	RoomName             pgtype.Text        `json:"room_name"`
	EquipmentUserName    pgtype.Text        `json:"equipment_user_name"`
}

// ============================================================
// PRINTERS (unitats)
// ============================================================
func (q *Queries) ListPrinters(ctx context.Context) ([]ListPrintersRow, error) {
	rows, err := q.db.Query(ctx, listPrinters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrintersRow
	for rows.Next() {
		var i ListPrintersRow
		if err := rows.Scan(
			&i.PrinterID,
			&i.Status,
			&i.HasNetworkCapability,
			&i.UsesNetwork,
			&i.IpAddress,
			&i.RoomID,
			&i.EquipmentUserID,
			&i.Observations,
			&i.CreatedByAppUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrinterModelID,
			&i.ModelName,
			&i.PrinterType,
			&i.PrintColor,
			&i.BrandID,
			&i.BrandName,
			&i.RoomName,
			&i.EquipmentUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliesByPrinterModel = `-- name: ListSuppliesByPrinterModel :many
SELECT ps.printer_supply_id, ps.name, ps.supply_type
FROM printer_supply ps
JOIN printer_model_supply pms ON pms.printer_supply_id = ps.printer_supply_id
WHERE pms.printer_model_id = $1
ORDER BY ps.name
`

func (q *Queries) ListSuppliesByPrinterModel(ctx context.Context, printerModelID int64) ([]PrinterSupply, error) {
	rows, err := q.db.Query(ctx, listSuppliesByPrinterModel, printerModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrinterSupply
	for rows.Next() {
		var i PrinterSupply
		if err := rows.Scan(&i.PrinterSupplyID, &i.Name, &i.SupplyType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePrinterModelSupply = `-- name: RemovePrinterModelSupply :exec
DELETE FROM printer_model_supply
WHERE printer_model_id = $1 AND printer_supply_id = $2
`

type RemovePrinterModelSupplyParams struct {
	PrinterModelID  int64 `json:"printer_model_id"`
	PrinterSupplyID int64 `json:"printer_supply_id"`
}

func (q *Queries) RemovePrinterModelSupply(ctx context.Context, arg RemovePrinterModelSupplyParams) error {
	_, err := q.db.Exec(ctx, removePrinterModelSupply, arg.PrinterModelID, arg.PrinterSupplyID)
	return err
}

const updatePrinter = `-- name: UpdatePrinter :one
UPDATE printer
SET
    printer_model_id       = COALESCE($1,       printer_model_id),
    status                 = COALESCE($2,                 status),
    has_network_capability = COALESCE($3, has_network_capability),
    uses_network           = COALESCE($4,           uses_network),
    ip_address             = COALESCE($5,             ip_address),
    room_id                = COALESCE($6,                room_id),
    equipment_user_id      = COALESCE($7,      equipment_user_id),
    observations           = COALESCE($8,           observations),
    updated_at             = now()
WHERE printer_id = $9
RETURNING printer_id, printer_model_id, status, has_network_capability, uses_network, ip_address, room_id, equipment_user_id, observations, created_by_app_user_id, created_at, updated_at
`

type UpdatePrinterParams struct {
	PrinterModelID       pgtype.Int8          `json:"printer_model_id"`
	Status               NullDeviceStatusEnum `json:"status"`
	HasNetworkCapability pgtype.Bool          `json:"has_network_capability"`
	UsesNetwork          pgtype.Bool          `json:"uses_network"`
	IpAddress            pgtype.Text          `json:"ip_address"`
	RoomID               pgtype.Int8          `json:"room_id"`
	EquipmentUserID      pgtype.Int8          `json:"equipment_user_id"`
	Observations         pgtype.Text          `json:"observations"`
	PrinterID            int64                `json:"printer_id"`
}

func (q *Queries) UpdatePrinter(ctx context.Context, arg UpdatePrinterParams) (Printer, error) {
	row := q.db.QueryRow(ctx, updatePrinter,
		arg.PrinterModelID,
		arg.Status,
		arg.HasNetworkCapability,
		arg.UsesNetwork,
		arg.IpAddress,
		arg.RoomID,
		arg.EquipmentUserID,
		arg.Observations,
		arg.PrinterID,
	)
	var i Printer
	err := row.Scan(
		&i.PrinterID,
		&i.PrinterModelID,
		&i.Status,
		&i.HasNetworkCapability,
		&i.UsesNetwork,
		&i.IpAddress,
		&i.RoomID,
		&i.EquipmentUserID,
		&i.Observations,
		&i.CreatedByAppUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePrinterModel = `-- name: UpdatePrinterModel :one
UPDATE printer_model
SET
    brand_id     = COALESCE($1,     brand_id),
    model_name   = COALESCE($2,   model_name),
    printer_type = COALESCE($3, printer_type),
    print_color  = COALESCE($4,  print_color)
WHERE printer_model_id = $5
RETURNING printer_model_id, brand_id, model_name, printer_type, print_color
`

type UpdatePrinterModelParams struct {
	BrandID        pgtype.Int8         `json:"brand_id"`
	ModelName      pgtype.Text         `json:"model_name"`
	PrinterType    NullPrinterTypeEnum `json:"printer_type"`
	PrintColor     NullPrintColorEnum  `json:"print_color"`
	PrinterModelID int64               `json:"printer_model_id"`
}

func (q *Queries) UpdatePrinterModel(ctx context.Context, arg UpdatePrinterModelParams) (PrinterModel, error) {
	row := q.db.QueryRow(ctx, updatePrinterModel,
		arg.BrandID,
		arg.ModelName,
		arg.PrinterType,
		arg.PrintColor,
		arg.PrinterModelID,
	)
	var i PrinterModel
	err := row.Scan(
		&i.PrinterModelID,
		&i.BrandID,
		&i.ModelName,
		&i.PrinterType,
		&i.PrintColor,
	)
	return i, err
}

const updatePrinterSupply = `-- name: UpdatePrinterSupply :one
UPDATE printer_supply
SET
    name        = COALESCE($1,        name),
    supply_type = COALESCE($2, supply_type)
WHERE printer_supply_id = $3
RETURNING printer_supply_id, name, supply_type
`

type UpdatePrinterSupplyParams struct {
	Name            pgtype.Text         `json:"name"`
	SupplyType      NullPrinterTypeEnum `json:"supply_type"`
	PrinterSupplyID int64               `json:"printer_supply_id"`
}

func (q *Queries) UpdatePrinterSupply(ctx context.Context, arg UpdatePrinterSupplyParams) (PrinterSupply, error) {
	row := q.db.QueryRow(ctx, updatePrinterSupply, arg.Name, arg.SupplyType, arg.PrinterSupplyID)
	var i PrinterSupply
	err := row.Scan(&i.PrinterSupplyID, &i.Name, &i.SupplyType)
	return i, err
}
