// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projectors.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjector = `-- name: CreateProjector :one
INSERT INTO projector (
    projector_model_id,
    serial_number,
    status,
    room_id,
    equipment_user_id,
    observations,
    created_by_app_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING projector_id, projector_model_id, serial_number, status, room_id, equipment_user_id, observations, created_by_app_user_id, created_at, updated_at
`

type CreateProjectorParams struct {
	ProjectorModelID   int64            `json:"projector_model_id"`
	SerialNumber       pgtype.Text      `json:"serial_number"`
	Status             DeviceStatusEnum `json:"status"`
	RoomID             pgtype.Int8      `json:"room_id"`
	EquipmentUserID    pgtype.Int8      `json:"equipment_user_id"`
	Observations       pgtype.Text      `json:"observations"`
	CreatedByAppUserID int64            `json:"created_by_app_user_id"`
}

func (q *Queries) CreateProjector(ctx context.Context, arg CreateProjectorParams) (Projector, error) {
	row := q.db.QueryRow(ctx, createProjector,
		arg.ProjectorModelID,
		arg.SerialNumber,
		arg.Status,
		arg.RoomID,
		arg.EquipmentUserID,
		arg.Observations,
		arg.CreatedByAppUserID,
	)
	var i Projector
	err := row.Scan(
		&i.ProjectorID,
		&i.ProjectorModelID,
		&i.SerialNumber,
		&i.Status,
		&i.RoomID,
		&i.EquipmentUserID,
		&i.Observations,
		&i.CreatedByAppUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectorModel = `-- name: CreateProjectorModel :one
INSERT INTO projector_model (brand_id, model_name)
VALUES ($1, $2)
RETURNING projector_model_id, brand_id, model_name
`

type CreateProjectorModelParams struct {
	BrandID   int64  `json:"brand_id"`
	ModelName string `json:"model_name"`
}

func (q *Queries) CreateProjectorModel(ctx context.Context, arg CreateProjectorModelParams) (ProjectorModel, error) {
	row := q.db.QueryRow(ctx, createProjectorModel, arg.BrandID, arg.ModelName)
	var i ProjectorModel
	err := row.Scan(&i.ProjectorModelID, &i.BrandID, &i.ModelName)
	return i, err
}

const deleteProjector = `-- name: DeleteProjector :exec
DELETE FROM projector WHERE projector_id = $1
`

func (q *Queries) DeleteProjector(ctx context.Context, projectorID int64) error {
	_, err := q.db.Exec(ctx, deleteProjector, projectorID)
	return err
}

const deleteProjectorModel = `-- name: DeleteProjectorModel :exec
DELETE FROM projector_model WHERE projector_model_id = $1
`

func (q *Queries) DeleteProjectorModel(ctx context.Context, projectorModelID int64) error {
	_, err := q.db.Exec(ctx, deleteProjectorModel, projectorModelID)
	return err
}

const getProjector = `-- name: GetProjector :one
SELECT
    p.projector_id, p.serial_number, p.status,
    p.room_id, p.equipment_user_id, p.observations,
    p.created_by_app_user_id, p.created_at, p.updated_at,
    p.projector_model_id,
    pm.model_name,
    pm.brand_id,
    b.name AS brand_name,
    r.name AS room_name,
    eu.name AS equipment_user_name
FROM projector p
JOIN projector_model pm ON pm.projector_model_id = p.projector_model_id
JOIN brand b ON b.brand_id = pm.brand_id
LEFT JOIN room r ON r.room_id = p.room_id
LEFT JOIN equipment_user eu ON eu.equipment_user_id = p.equipment_user_id
WHERE p.projector_id = $1
`

type GetProjectorRow struct {
	ProjectorID        int64              `json:"projector_id"`
	SerialNumber       pgtype.Text        `json:"serial_number"`
	Status             DeviceStatusEnum   `json:"status"`
	RoomID             pgtype.Int8        `json:"room_id"`
	EquipmentUserID    pgtype.Int8        `json:"equipment_user_id"`
	Observations       pgtype.Text        `json:"observations"`
	CreatedByAppUserID int64              `json:"created_by_app_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ProjectorModelID   int64              `json:"projector_model_id"`
	ModelName          string             `json:"model_name"`
	BrandID            int64              `json:"brand_id"`
	BrandName          string             `json:"brand_name"`
	RoomName           pgtype.Text        `json:"room_name"`
	EquipmentUserName  pgtype.Text        `json:"equipment_user_name"`
}

func (q *Queries) GetProjector(ctx context.Context, projectorID int64) (GetProjectorRow, error) {
	row := q.db.QueryRow(ctx, getProjector, projectorID)
	var i GetProjectorRow
	err := row.Scan(
		&i.ProjectorID,
		&i.SerialNumber,
		&i.Status,
		&i.RoomID,
		&i.EquipmentUserID,
		&i.Observations,
		&i.CreatedByAppUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectorModelID,
		&i.ModelName,
		&i.BrandID,
		&i.BrandName,
		&i.RoomName,
		&i.EquipmentUserName,
	)
	return i, err
}

const getProjectorModel = `-- name: GetProjectorModel :one
SELECT pm.projector_model_id, pm.brand_id, pm.model_name, b.name AS brand_name
FROM projector_model pm
JOIN brand b ON b.brand_id = pm.brand_id
WHERE pm.projector_model_id = $1
`

type GetProjectorModelRow struct {
	ProjectorModelID int64  `json:"projector_model_id"`
	BrandID          int64  `json:"brand_id"`
	ModelName        string `json:"model_name"`
	BrandName        string `json:"brand_name"`
}

func (q *Queries) GetProjectorModel(ctx context.Context, projectorModelID int64) (GetProjectorModelRow, error) {
	row := q.db.QueryRow(ctx, getProjectorModel, projectorModelID)
	var i GetProjectorModelRow
	err := row.Scan(
		&i.ProjectorModelID,
		&i.BrandID,
		&i.ModelName,
		&i.BrandName,
	)
	return i, err
}

const listProjectorModels = `-- name: ListProjectorModels :many

SELECT pm.projector_model_id, pm.brand_id, pm.model_name, b.name AS brand_name
FROM projector_model pm
JOIN brand b ON b.brand_id = pm.brand_id
ORDER BY b.name, pm.model_name
`

type ListProjectorModelsRow struct {
	ProjectorModelID int64  `json:"projector_model_id"`
	BrandID          int64  `json:"brand_id"`
	ModelName        string `json:"model_name"`
	BrandName        string `json:"brand_name"`
}

// ============================================================
// PROJECTOR MODELS
// ============================================================
func (q *Queries) ListProjectorModels(ctx context.Context) ([]ListProjectorModelsRow, error) {
	rows, err := q.db.Query(ctx, listProjectorModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectorModelsRow
	for rows.Next() {
		var i ListProjectorModelsRow
		if err := rows.Scan(
			&i.ProjectorModelID,
			&i.BrandID,
			&i.ModelName,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectors = `-- name: ListProjectors :many

SELECT
    p.projector_id, p.serial_number, p.status,
    p.room_id, p.equipment_user_id, p.observations,
    p.created_by_app_user_id, p.created_at, p.updated_at,
    p.projector_model_id,
    pm.model_name,
    pm.brand_id,
    b.name AS brand_name,
    r.name AS room_name,
    eu.name AS equipment_user_name
FROM projector p
JOIN projector_model pm ON pm.projector_model_id = p.projector_model_id
JOIN brand b ON b.brand_id = pm.brand_id
LEFT JOIN room r ON r.room_id = p.room_id
LEFT JOIN equipment_user eu ON eu.equipment_user_id = p.equipment_user_id
ORDER BY p.projector_id
`

type ListProjectorsRow struct {
	ProjectorID        int64              `json:"projector_id"`
	SerialNumber       pgtype.Text        `json:"serial_number"`
	Status             DeviceStatusEnum   `json:"status"`
	RoomID             pgtype.Int8        `json:"room_id"`
	EquipmentUserID    pgtype.Int8        `json:"equipment_user_id"`
	Observations       pgtype.Text        `json:"observations"`
	CreatedByAppUserID int64              `json:"created_by_app_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ProjectorModelID   int64              `json:"projector_model_id"`
	ModelName          string             `json:"model_name"`
	BrandID            int64              `json:"brand_id"`
	BrandName          string             `json:"brand_name"`
	RoomName           pgtype.Text        `json:"room_name"`
	EquipmentUserName  pgtype.Text        `json:"equipment_user_name"`
}

// ============================================================
// PROJECTORS (unitats)
// ============================================================
func (q *Queries) ListProjectors(ctx context.Context) ([]ListProjectorsRow, error) {
	rows, err := q.db.Query(ctx, listProjectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectorsRow
	for rows.Next() {
		var i ListProjectorsRow
		if err := rows.Scan(
			&i.ProjectorID,
			&i.SerialNumber,
			&i.Status,
			&i.RoomID,
			&i.EquipmentUserID,
			&i.Observations,
			&i.CreatedByAppUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectorModelID,
			&i.ModelName,
			&i.BrandID,
			&i.BrandName,
			&i.RoomName,
			&i.EquipmentUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjector = `-- name: UpdateProjector :one
UPDATE projector
SET
    projector_model_id = COALESCE($1, projector_model_id),
    serial_number      = COALESCE($2,      serial_number),
    status             = COALESCE($3,             status),
    room_id            = COALESCE($4,            room_id),
    equipment_user_id  = COALESCE($5,  equipment_user_id),
    observations       = COALESCE($6,       observations),
    updated_at         = now()
WHERE projector_id = $7
RETURNING projector_id, projector_model_id, serial_number, status, room_id, equipment_user_id, observations, created_by_app_user_id, created_at, updated_at
`

type UpdateProjectorParams struct {
	ProjectorModelID pgtype.Int8          `json:"projector_model_id"`
	SerialNumber     pgtype.Text          `json:"serial_number"`
	Status           NullDeviceStatusEnum `json:"status"`
	RoomID           pgtype.Int8          `json:"room_id"`
	EquipmentUserID  pgtype.Int8          `json:"equipment_user_id"`
	Observations     pgtype.Text          `json:"observations"`
	ProjectorID      int64                `json:"projector_id"`
}

func (q *Queries) UpdateProjector(ctx context.Context, arg UpdateProjectorParams) (Projector, error) {
	row := q.db.QueryRow(ctx, updateProjector,
		arg.ProjectorModelID,
		arg.SerialNumber,
		arg.Status,
		arg.RoomID,
		arg.EquipmentUserID,
		arg.Observations,
		arg.ProjectorID,
	)
	var i Projector
	err := row.Scan(
		&i.ProjectorID,
		&i.ProjectorModelID,
		&i.SerialNumber,
		&i.Status,
		&i.RoomID,
		&i.EquipmentUserID,
		&i.Observations,
		&i.CreatedByAppUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectorModel = `-- name: UpdateProjectorModel :one
UPDATE projector_model
SET
    brand_id   = COALESCE($1,   brand_id),
    model_name = COALESCE($2, model_name)
WHERE projector_model_id = $3
RETURNING projector_model_id, brand_id, model_name
`

type UpdateProjectorModelParams struct {
	BrandID          pgtype.Int8 `json:"brand_id"`
	ModelName        pgtype.Text `json:"model_name"`
	ProjectorModelID int64       `json:"projector_model_id"`
}

func (q *Queries) UpdateProjectorModel(ctx context.Context, arg UpdateProjectorModelParams) (ProjectorModel, error) {
	row := q.db.QueryRow(ctx, updateProjectorModel, arg.BrandID, arg.ModelName, arg.ProjectorModelID)
	var i ProjectorModel
	err := row.Scan(&i.ProjectorModelID, &i.BrandID, &i.ModelName)
	return i, err
}
