// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO role (role_id, description)
VALUES ($1, $2)
RETURNING role_id, description
`

type CreateRoleParams struct {
	RoleID      string      `json:"role_id"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.RoleID, arg.Description)
	var i Role
	err := row.Scan(&i.RoleID, &i.Description)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM role WHERE role_id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, deleteRole, roleID)
	return err
}

const listRoles = `-- name: ListRoles :many
SELECT role_id, description FROM role ORDER BY role_id
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
