// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package dbsqlc

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO room (center_id, name)
VALUES ($1, $2)
RETURNING room_id, center_id, name
`

type CreateRoomParams struct {
	CenterID int64  `json:"center_id"`
	Name     string `json:"name"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.CenterID, arg.Name)
	var i Room
	err := row.Scan(&i.RoomID, &i.CenterID, &i.Name)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM room
WHERE room_id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, roomID int64) error {
	_, err := q.db.Exec(ctx, deleteRoom, roomID)
	return err
}

const listRoomsByCenter = `-- name: ListRoomsByCenter :many
SELECT room_id, center_id, name
FROM room
WHERE center_id = $1
ORDER BY room_id
`

func (q *Queries) ListRoomsByCenter(ctx context.Context, centerID int64) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsByCenter, centerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(&i.RoomID, &i.CenterID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE room
SET name = $1
WHERE room_id = $2
RETURNING room_id, center_id, name
`

type UpdateRoomParams struct {
	Name   string `json:"name"`
	RoomID int64  `json:"room_id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom, arg.Name, arg.RoomID)
	var i Room
	err := row.Scan(&i.RoomID, &i.CenterID, &i.Name)
	return i, err
}
