// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: school_classes.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClass = `-- name: CreateClass :one
INSERT INTO school_class (cycle_id, course, class_label, shift, tutor_app_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING class_id, cycle_id, course, class_label, shift, tutor_app_user_id
`

type CreateClassParams struct {
	CycleID        int64       `json:"cycle_id"`
	Course         int16       `json:"course"`
	ClassLabel     string      `json:"class_label"`
	Shift          ShiftEnum   `json:"shift"`
	TutorAppUserID pgtype.Int8 `json:"tutor_app_user_id"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (SchoolClass, error) {
	row := q.db.QueryRow(ctx, createClass,
		arg.CycleID,
		arg.Course,
		arg.ClassLabel,
		arg.Shift,
		arg.TutorAppUserID,
	)
	var i SchoolClass
	err := row.Scan(
		&i.ClassID,
		&i.CycleID,
		&i.Course,
		&i.ClassLabel,
		&i.Shift,
		&i.TutorAppUserID,
	)
	return i, err
}

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM school_class WHERE class_id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, classID int64) error {
	_, err := q.db.Exec(ctx, deleteClass, classID)
	return err
}

const getClass = `-- name: GetClass :one
SELECT class_id, cycle_id, course, class_label, shift, tutor_app_user_id FROM school_class WHERE class_id = $1
`

func (q *Queries) GetClass(ctx context.Context, classID int64) (SchoolClass, error) {
	row := q.db.QueryRow(ctx, getClass, classID)
	var i SchoolClass
	err := row.Scan(
		&i.ClassID,
		&i.CycleID,
		&i.Course,
		&i.ClassLabel,
		&i.Shift,
		&i.TutorAppUserID,
	)
	return i, err
}

const listClasses = `-- name: ListClasses :many
SELECT sc.class_id, sc.cycle_id, sc.course, sc.class_label, sc.shift, sc.tutor_app_user_id, cy.name AS cycle_name
FROM school_class sc
JOIN cycle cy ON cy.cycle_id = sc.cycle_id
ORDER BY cy.name, sc.course, sc.class_label
`

type ListClassesRow struct {
	ClassID        int64       `json:"class_id"`
	CycleID        int64       `json:"cycle_id"`
	Course         int16       `json:"course"`
	ClassLabel     string      `json:"class_label"`
	Shift          ShiftEnum   `json:"shift"`
	TutorAppUserID pgtype.Int8 `json:"tutor_app_user_id"`
	CycleName      string      `json:"cycle_name"`
}

func (q *Queries) ListClasses(ctx context.Context) ([]ListClassesRow, error) {
	rows, err := q.db.Query(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassesRow
	for rows.Next() {
		var i ListClassesRow
		if err := rows.Scan(
			&i.ClassID,
			&i.CycleID,
			&i.Course,
			&i.ClassLabel,
			&i.Shift,
			&i.TutorAppUserID,
			&i.CycleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesByCycle = `-- name: ListClassesByCycle :many
SELECT sc.class_id, sc.cycle_id, sc.course, sc.class_label, sc.shift, sc.tutor_app_user_id, cy.name AS cycle_name
FROM school_class sc
JOIN cycle cy ON cy.cycle_id = sc.cycle_id
WHERE sc.cycle_id = $1
ORDER BY sc.course, sc.class_label
`

type ListClassesByCycleRow struct {
	ClassID        int64       `json:"class_id"`
	CycleID        int64       `json:"cycle_id"`
	Course         int16       `json:"course"`
	ClassLabel     string      `json:"class_label"`
	Shift          ShiftEnum   `json:"shift"`
	TutorAppUserID pgtype.Int8 `json:"tutor_app_user_id"`
	CycleName      string      `json:"cycle_name"`
}

func (q *Queries) ListClassesByCycle(ctx context.Context, cycleID int64) ([]ListClassesByCycleRow, error) {
	rows, err := q.db.Query(ctx, listClassesByCycle, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassesByCycleRow
	for rows.Next() {
		var i ListClassesByCycleRow
		if err := rows.Scan(
			&i.ClassID,
			&i.CycleID,
			&i.Course,
			&i.ClassLabel,
			&i.Shift,
			&i.TutorAppUserID,
			&i.CycleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesByTutor = `-- name: ListClassesByTutor :many
SELECT sc.class_id, sc.cycle_id, sc.course, sc.class_label, sc.shift, sc.tutor_app_user_id, cy.name AS cycle_name
FROM school_class sc
JOIN cycle cy ON cy.cycle_id = sc.cycle_id
WHERE sc.tutor_app_user_id = $1
ORDER BY cy.name, sc.course, sc.class_label
`

type ListClassesByTutorRow struct {
	ClassID        int64       `json:"class_id"`
	CycleID        int64       `json:"cycle_id"`
	Course         int16       `json:"course"`
	ClassLabel     string      `json:"class_label"`
	Shift          ShiftEnum   `json:"shift"`
	TutorAppUserID pgtype.Int8 `json:"tutor_app_user_id"`
	CycleName      string      `json:"cycle_name"`
}

func (q *Queries) ListClassesByTutor(ctx context.Context, tutorAppUserID pgtype.Int8) ([]ListClassesByTutorRow, error) {
	rows, err := q.db.Query(ctx, listClassesByTutor, tutorAppUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassesByTutorRow
	for rows.Next() {
		var i ListClassesByTutorRow
		if err := rows.Scan(
			&i.ClassID,
			&i.CycleID,
			&i.Course,
			&i.ClassLabel,
			&i.Shift,
			&i.TutorAppUserID,
			&i.CycleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :one
UPDATE school_class
SET
    class_label       = COALESCE($1,       class_label),
    shift             = COALESCE($2,             shift),
    tutor_app_user_id = COALESCE($3, tutor_app_user_id)
WHERE class_id = $4
RETURNING class_id, cycle_id, course, class_label, shift, tutor_app_user_id
`

type UpdateClassParams struct {
	ClassLabel     pgtype.Text   `json:"class_label"`
	Shift          NullShiftEnum `json:"shift"`
	TutorAppUserID pgtype.Int8   `json:"tutor_app_user_id"`
	ClassID        int64         `json:"class_id"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (SchoolClass, error) {
	row := q.db.QueryRow(ctx, updateClass,
		arg.ClassLabel,
		arg.Shift,
		arg.TutorAppUserID,
		arg.ClassID,
	)
	var i SchoolClass
	err := row.Scan(
		&i.ClassID,
		&i.CycleID,
		&i.Course,
		&i.ClassLabel,
		&i.Shift,
		&i.TutorAppUserID,
	)
	return i, err
}
