// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO student (full_name, class_id)
VALUES ($1, $2)
RETURNING student_id, full_name, class_id
`

type CreateStudentParams struct {
	FullName string `json:"full_name"`
	ClassID  int64  `json:"class_id"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.FullName, arg.ClassID)
	var i Student
	err := row.Scan(&i.StudentID, &i.FullName, &i.ClassID)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM student WHERE student_id = $1
`

func (q *Queries) DeleteStudent(ctx context.Context, studentID int64) error {
	_, err := q.db.Exec(ctx, deleteStudent, studentID)
	return err
}

const getStudent = `-- name: GetStudent :one
SELECT student_id, full_name, class_id FROM student WHERE student_id = $1
`

func (q *Queries) GetStudent(ctx context.Context, studentID int64) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, studentID)
	var i Student
	err := row.Scan(&i.StudentID, &i.FullName, &i.ClassID)
	return i, err
}

const listStudentsByClass = `-- name: ListStudentsByClass :many
SELECT student_id, full_name, class_id FROM student WHERE class_id = $1 ORDER BY full_name
`

func (q *Queries) ListStudentsByClass(ctx context.Context, classID int64) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudentsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(&i.StudentID, &i.FullName, &i.ClassID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE student
SET
    full_name = COALESCE($1, full_name),
    class_id  = COALESCE($2,  class_id)
WHERE student_id = $3
RETURNING student_id, full_name, class_id
`

type UpdateStudentParams struct {
	FullName  pgtype.Text `json:"full_name"`
	ClassID   pgtype.Int8 `json:"class_id"`
	StudentID int64       `json:"student_id"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent, arg.FullName, arg.ClassID, arg.StudentID)
	var i Student
	err := row.Scan(&i.StudentID, &i.FullName, &i.ClassID)
	return i, err
}
