// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO app_user (username, password_hash, role_id)
VALUES ($1, $2, $3)
RETURNING app_user_id, username, role_id
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	RoleID       string `json:"role_id"`
}

type CreateUserRow struct {
	AppUserID int64  `json:"app_user_id"`
	Username  string `json:"username"`
	RoleID    string `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.RoleID)
	var i CreateUserRow
	err := row.Scan(&i.AppUserID, &i.Username, &i.RoleID)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM app_user
WHERE app_user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, appUserID int64) error {
	_, err := q.db.Exec(ctx, deleteUser, appUserID)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT app_user_id, username, role_id
FROM app_user
ORDER BY app_user_id
`

type ListUsersRow struct {
	AppUserID int64  `json:"app_user_id"`
	Username  string `json:"username"`
	RoleID    string `json:"role_id"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.AppUserID, &i.Username, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE app_user
SET
    username = COALESCE($1, username),
    role_id  = COALESCE($2,  role_id)
WHERE app_user_id = $3
RETURNING app_user_id, username, role_id
`

type UpdateUserParams struct {
	Username  pgtype.Text `json:"username"`
	RoleID    pgtype.Text `json:"role_id"`
	AppUserID int64       `json:"app_user_id"`
}

type UpdateUserRow struct {
	AppUserID int64  `json:"app_user_id"`
	Username  string `json:"username"`
	RoleID    string `json:"role_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Username, arg.RoleID, arg.AppUserID)
	var i UpdateUserRow
	err := row.Scan(&i.AppUserID, &i.Username, &i.RoleID)
	return i, err
}
