// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO app_user (username, password_hash, can_create, can_update, can_delete, is_meta)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING app_user_id, username, can_create, can_update, can_delete, is_meta
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	CanCreate    bool   `json:"can_create"`
	CanUpdate    bool   `json:"can_update"`
	CanDelete    bool   `json:"can_delete"`
	IsMeta       bool   `json:"is_meta"`
}

type CreateUserRow struct {
	AppUserID int64  `json:"app_user_id"`
	Username  string `json:"username"`
	CanCreate bool   `json:"can_create"`
	CanUpdate bool   `json:"can_update"`
	CanDelete bool   `json:"can_delete"`
	IsMeta    bool   `json:"is_meta"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.CanCreate,
		arg.CanUpdate,
		arg.CanDelete,
		arg.IsMeta,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.AppUserID,
		&i.Username,
		&i.CanCreate,
		&i.CanUpdate,
		&i.CanDelete,
		&i.IsMeta,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM app_user
WHERE app_user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, appUserID int64) error {
	_, err := q.db.Exec(ctx, deleteUser, appUserID)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT app_user_id, username, can_create, can_update, can_delete, is_meta
FROM app_user
ORDER BY app_user_id
`

type ListUsersRow struct {
	AppUserID int64  `json:"app_user_id"`
	Username  string `json:"username"`
	CanCreate bool   `json:"can_create"`
	CanUpdate bool   `json:"can_update"`
	CanDelete bool   `json:"can_delete"`
	IsMeta    bool   `json:"is_meta"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.AppUserID,
			&i.Username,
			&i.CanCreate,
			&i.CanUpdate,
			&i.CanDelete,
			&i.IsMeta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE app_user
SET
    username   = COALESCE($1,   username),
    can_create = COALESCE($2, can_create),
    can_update = COALESCE($3, can_update),
    can_delete = COALESCE($4, can_delete),
    is_meta    = COALESCE($5,    is_meta)
WHERE app_user_id = $6
RETURNING app_user_id, username, can_create, can_update, can_delete, is_meta
`

type UpdateUserParams struct {
	Username  pgtype.Text `json:"username"`
	CanCreate pgtype.Bool `json:"can_create"`
	CanUpdate pgtype.Bool `json:"can_update"`
	CanDelete pgtype.Bool `json:"can_delete"`
	IsMeta    pgtype.Bool `json:"is_meta"`
	AppUserID int64       `json:"app_user_id"`
}

type UpdateUserRow struct {
	AppUserID int64  `json:"app_user_id"`
	Username  string `json:"username"`
	CanCreate bool   `json:"can_create"`
	CanUpdate bool   `json:"can_update"`
	CanDelete bool   `json:"can_delete"`
	IsMeta    bool   `json:"is_meta"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.CanCreate,
		arg.CanUpdate,
		arg.CanDelete,
		arg.IsMeta,
		arg.AppUserID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.AppUserID,
		&i.Username,
		&i.CanCreate,
		&i.CanUpdate,
		&i.CanDelete,
		&i.IsMeta,
	)
	return i, err
}
